In [1]:
import pandas as pd
import numpy as np
from glob import glob
from IPython.display import display
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 99)
import EDA
import utils
#sorted(glob('../data/*'))

In [2]:
df = utils.read_pickles('../data/POS_CASH_balance').sort_values(['SK_ID_CURR', 'MONTHS_BALANCE'], ascending=[True, False])
df.head()

100%|██████████| 20/20 [00:05<00:00,  3.42it/s]

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
2197888,1369693,100001,-53,4.0,0.0,Completed,0,0
4704415,1369693,100001,-54,4.0,1.0,Active,0,0
7823681,1369693,100001,-55,4.0,2.0,Active,0,0
8789081,1369693,100001,-56,4.0,3.0,Active,0,0
7167007,1369693,100001,-57,4.0,4.0,Active,0,0

In [3]:
EDA.df_info(df)

Shape: (10001358, 8)

,DataType,#Nulls,#Uniques,Min,Mean,Max,Std,top10 val,top10 cnt
SK_ID_PREV,int64,0,936325,1000001.0,1.903217e+06,2843499.0,535846.530722,"[1624618, 2746611, 1889497, 1235285, 2263451, ...","[96, 96, 96, 96, 96, 96, 96, 96, 96, 96]"
SK_ID_CURR,int64,0,337252,100001.0,2.784039e+05,456255.0,102763.745090,"[265042, 172612, 309133, 197583, 127659, 18518...","[295, 247, 246, 245, 245, 245, 244, 239, 237, ..."
MONTHS_BALANCE,int64,0,96,-96.0,-3.501259e+01,-1.0,26.066570,"[-10, -11, -9, -12, -8, -13, -7, -14, -6, -15]","[216441, 216023, 215558, 214716, 214149, 21095..."
CNT_INSTALMENT,float64,26071,73,1.0,1.708965e+01,92.0,11.995056,"[12.0, 24.0, 10.0, 6.0, 18.0, 36.0, 8.0, 48.0,...","[2496845, 1517472, 1243449, 1065500, 727394, 5..."
CNT_INSTALMENT_FUTURE,float64,26087,79,0.0,1.048384e+01,85.0,11.109058,"[0.0, 6.0, 4.0, 5.0, 3.0, 2.0, 1.0, 10.0, 8.0,...","[1185960, 614058, 613632, 600295, 582007, 5471..."
NAME_CONTRACT_STATUS,object,0,9,NaN,NaN,NaN,NaN,"['Active', 'Completed', 'Signed', 'Demand', 'R...","[9151119, 744883, 87260, 7065, 5461, 4917, 636..."
SK_DPD,int64,0,3400,0.0,1.160693e+01,4231.0,132.714043,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[9706131, 21872, 17358, 14403, 12350, 11046, 9..."
SK_DPD_DEF,int64,0,2307,0.0,6.544684e-01,3595.0,32.762491,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]","[9887389, 22134, 14690, 11652, 9528, 8031, 662..."

In [3]:
ids = df.SK_ID_CURR.unique()

In [4]:
tmp = df[df.SK_ID_CURR==np.random.choice(ids)]
tmp

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
7735592,1175665,442493,-47,18.0,0.0,Completed,0,0
9048888,1175665,442493,-48,18.0,0.0,Active,0,0
6284754,1175665,442493,-49,18.0,1.0,Active,1,1
6785606,1175665,442493,-50,18.0,2.0,Active,0,0
7163550,1175665,442493,-51,18.0,4.0,Active,0,0
7197272,1175665,442493,-52,18.0,5.0,Active,0,0
772597,1175665,442493,-53,18.0,6.0,Active,0,0
7091152,1175665,442493,-54,18.0,7.0,Active,0,0
5395161,1175665,442493,-55,18.0,8.0,Active,0,0
3062531,1175665,442493,-56,18.0,9.0,Active,0,0
4768629,1175665,442493,-57,18.0,10.0,Active,0,0
7869523,1175665,442493,-58,18.0,11.0,Active,0,0
3889251,1175665,442493,-59,18.0,12.0,Active,0,0
12316,1175665,442493,-60,18.0,13.0,Active,0,0
7198433,1175665,442493,-61,18.0,14.0,Active,0,0
7090413,1175665,442493,-62,18.0,15.0,Active,0,0
7304628,1175665,442493,-63,18.0,16.0,Active,0,0
8967947,1175665,442493,-64,18.0,17.0,Active,0,0
7735257,1175665,442493,-65,18.0,18.0,Active,0,0

In [4]:
tmp = df[df.SK_ID_CURR.isin(np.random.choice(ids, size=9))]
tmp

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
2394473,1752609,127809,-1,36.0,30.0,Active,0,0
4255103,1752609,127809,-2,36.0,31.0,Active,0,0
5725905,1752609,127809,-3,36.0,32.0,Active,0,0
3988848,1752609,127809,-4,36.0,33.0,Active,0,0
3094517,1752609,127809,-5,36.0,34.0,Active,0,0
1661930,1752609,127809,-6,36.0,35.0,Active,0,0
2329334,1752609,127809,-7,36.0,36.0,Active,0,0
4545022,1244508,127809,-19,25.0,0.0,Completed,0,0
6414815,1420504,127809,-19,11.0,0.0,Completed,0,0
1040537,1244508,127809,-20,36.0,12.0,Active,0,0
1787458,1420504,127809,-20,11.0,0.0,Active,0,0
2307135,1420504,127809,-21,42.0,32.0,Active,0,0
2312287,1244508,127809,-21,36.0,13.0,Active,0,0
3658283,1420504,127809,-22,42.0,33.0,Active,0,0
3835887,1244508,127809,-22,36.0,14.0,Active,0,0
368845,1420504,127809,-23,42.0,34.0,Active,0,0
1431440,1244508,127809,-23,36.0,15.0,Active,0,0
4031112,1244508,127809,-24,36.0,16.0,Active,0,0
5197797,1420504,127809,-24,42.0,35.0,Active,0,0
2324229,1244508,127809,-25,36.0,17.0,Active,0,0
2944762,1420504,127809,-25,42.0,36.0,Active,0,0
1124606,1420504,127809,-26,42.0,37.0,Active,0,0
1925997,1244508,127809,-26,36.0,18.0,Active,0,0
4344440,1420504,127809,-27,42.0,38.0,Active,2,2
4798847,1244508,127809,-27,36.0,19.0,Active,0,0
2316949,1244508,127809,-28,36.0,20.0,Active,0,0
3538307,1420504,127809,-28,42.0,39.0,Active,0,0
3276755,1244508,127809,-29,36.0,21.0,Active,0,0
3528409,1420504,127809,-29,42.0,40.0,Active,0,0
4153276,1244508,127809,-30,36.0,22.0,Active,0,0
4155054,1468000,127809,-30,5.0,0.0,Completed,0,0
7871821,1420504,127809,-30,42.0,42.0,Active,0,0
4100336,1244508,127809,-31,36.0,23.0,Active,0,0
4996608,1468000,127809,-31,5.0,1.0,Active,0,0
3743860,1244508,127809,-32,36.0,24.0,Active,0,0
4404137,1468000,127809,-32,24.0,22.0,Active,0,0
4736595,1468000,127809,-33,24.0,23.0,Active,0,0
4875202,1244508,127809,-33,36.0,25.0,Active,0,0
8048621,2180747,127809,-33,2.0,0.0,Completed,0,0
4760255,1244508,127809,-34,36.0,26.0,Active,0,0
4795208,2180747,127809,-34,2.0,0.0,Active,0,0
8176574,1468000,127809,-34,24.0,24.0,Active,0,0
2757481,2180747,127809,-35,12.0,11.0,Active,0,0
3966067,1244508,127809,-35,36.0,27.0,Active,0,0
4836512,2651813,127809,-35,10.0,0.0,Completed,0,0
1163139,1244508,127809,-36,36.0,28.0,Active,0,0
2869321,2180747,127809,-36,12.0,12.0,Active,0,0
8340162,2651813,127809,-36,12.0,3.0,Active,0,0
1229873,2651813,127809,-37,12.0,4.0,Active,0,0
...,...,...,...,...,...,...,...,...
6541337,1417827,444829,-17,24.0,2.0,Active,0,0
8277094,1417827,444829,-18,24.0,3.0,Active,0,0
8089456,1417827,444829,-19,24.0,4.0,Active,0,0
6539660,1417827,444829,-20,24.0,5.0,Active,0,0
9866623,1417827,444829,-21,24.0,6.0,Active,0,0
7359094,1417827,444829,-22,24.0,7.0,Active,0,0
8323892,1417827,444829,-23,24.0,8.0,Active,0,0
8325457,1417827,444829,-24,24.0,9.0,Active,0,0
6573766,1417827,444829,-25,24.0,10.0,Active,0,0
6673872,1417827,444829,-26,24.0,11.0,Active,0,0
2206149,1417827,444829,-27,24.0,12.0,Active,0,0
1777990,1417827,444829,-28,24.0,13.0,Active,0,0
628692,1417827,444829,-29,24.0,14.0,Active,0,0
4946921,1417827,444829,-30,24.0,15.0,Active,0,0
9033779,1417827,444829,-31,24.0,16.0,Active,0,0
5684866,1417827,444829,-32,24.0,17.0,Active,0,0
5601329,1417827,444829,-33,24.0,18.0,Active,0,0
8805686,1417827,444829,-34,24.0,19.0,Active,0,0
5495112,1417827,444829,-35,24.0,20.0,Active,0,0
479441,1417827,444829,-36,24.0,21.0,Active,0,0
9288910,1417827,444829,-37,24.0,22.0,Active,0,0
4949900,1417827,444829,-38,24.0,23.0,Active,0,0
5830062,1417827,444829,-39,24.0,24.0,Active,0,0
6383120,1306079,444829,-39,10.0,0.0,Completed,0,0
4484272,1306079,444829,-40,10.0,1.0,Active,0,0
1146623,1306079,444829,-41,10.0,2.0,Active,0,0
135265,1306079,444829,-42,10.0,3.0,Active,0,0
2538098,1306079,444829,-43,10.0,4.0,Active,0,0
468471,1306079,444829,-44,10.0,5.0,Active,0,0
2042395,1306079,444829,-45,10.0,6.0,Active,0,0
2799159,1306079,444829,-46,10.0,7.0,Active,0,0
4123773,1306079,444829,-47,10.0,8.0,Active,0,0
3304353,1306079,444829,-48,10.0,9.0,Active,0,0
4467156,1306079,444829,-49,10.0,10.0,Active,0,0
7100474,1231872,451760,-4,4.0,0.0,Completed,0,0
8318405,1231872,451760,-5,12.0,9.0,Active,0,0
6227696,1231872,451760,-6,12.0,10.0,Active,0,0
9535686,1231872,451760,-7,12.0,11.0,Active,0,0
9764547,1231872,451760,-8,12.0,12.0,Active,0,0
2569622,2736710,451760,-26,9.0,0.0,Completed,0,0
3462700,2736710,451760,-27,12.0,4.0,Active,0,0
1782781,2736710,451760,-28,12.0,5.0,Active,0,0
5637273,2736710,451760,-29,12.0,6.0,Active,0,0
8316575,2736710,451760,-30,12.0,7.0,Active,0,0
5095566,2736710,451760,-31,12.0,8.0,Active,0,0
8483094,2736710,451760,-32,12.0,9.0,Active,0,0
7988583,2736710,451760,-33,12.0,10.0,Active,0,0
1085883,2736710,451760,-34,12.0,11.0,Active,0,0
8618626,2736710,451760,-35,12.0,12.0,Active,0,0

In [5]:
tmp.to_csv('sample_POS.csv', index=False)