In [1]:
import pandas as pd
from glob import glob
from IPython.display import display
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 99)
import EDA
import utils

In [2]:
sorted(glob('../input/*'))

['../input/HomeCredit_columns_description.csv',
 '../input/POS_CASH_balance.csv.zip',
 '../input/application_test.csv.zip',
 '../input/application_train.csv.zip',
 '../input/bureau.csv.zip',
 '../input/bureau_balance.csv.zip',
 '../input/credit_card_balance.csv.zip',
 '../input/installments_payments.csv.zip',
 '../input/previous_application.csv.zip',
 '../input/sample_submission.csv.zip']

In [3]:
bureau = pd.read_csv('../input/bureau.csv.zip')
bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [4]:
EDA.df_info(bureau)

Shape: (1716428, 17)

                       DataType   #Nulls  #Uniques
SK_ID_CURR                int64        0    305811
SK_ID_BUREAU              int64        0   1716428
CREDIT_ACTIVE            object        0         4
CREDIT_CURRENCY          object        0         4
DAYS_CREDIT               int64        0      2923
CREDIT_DAY_OVERDUE        int64        0       942
DAYS_CREDIT_ENDDATE     float64   105553     14096
DAYS_ENDDATE_FACT       float64   633653      2917
AMT_CREDIT_MAX_OVERDUE  float64  1124488     68251
CNT_CREDIT_PROLONG        int64        0        10
AMT_CREDIT_SUM          float64       13    236708
AMT_CREDIT_SUM_DEBT     float64   257669    226537
AMT_CREDIT_SUM_LIMIT    float64   591780     51726
AMT_CREDIT_SUM_OVERDUE  float64        0      1616
CREDIT_TYPE              object        0        15
DAYS_CREDIT_UPDATE        int64        0      2982
AMT_ANNUITY             float64  1226791     40321

In [5]:
bureau.sort_values(['SK_ID_CURR', 'DAYS_CREDIT'], inplace=True)
bureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
248487,100001,5896633,Closed,currency 1,-1572,0,-1329.0,-1328.0,NaN,0,85500.000,0.000,0.000,0.0,Consumer credit,-155,0.000
248485,100001,5896631,Closed,currency 1,-909,0,-179.0,-877.0,NaN,0,279720.000,0.000,0.000,0.0,Consumer credit,-155,0.000
248486,100001,5896632,Closed,currency 1,-879,0,-514.0,-544.0,NaN,0,91620.000,0.000,0.000,0.0,Consumer credit,-155,0.000
248484,100001,5896630,Closed,currency 1,-857,0,-492.0,-553.0,NaN,0,112500.000,0.000,0.000,0.0,Consumer credit,-155,0.000
248488,100001,5896634,Active,currency 1,-559,0,902.0,NaN,NaN,0,337680.000,113166.000,0.000,0.0,Consumer credit,-6,4630.500
248490,100001,5896636,Active,currency 1,-320,0,411.0,NaN,NaN,0,168345.000,110281.500,NaN,0.0,Consumer credit,-10,9364.500
248489,100001,5896635,Active,currency 1,-49,0,1778.0,NaN,NaN,0,378000.000,373239.000,0.000,0.0,Consumer credit,-16,10822.500
675686,100002,6158906,Closed,currency 1,-1437,0,-1072.0,-1185.0,0.000,0,135000.000,0.000,0.000,0.0,Consumer credit,-1185,0.000
675684,100002,6158904,Closed,currency 1,-1125,0,-1038.0,-1038.0,NaN,0,40761.000,NaN,NaN,0.0,Credit card,-1038,0.000
675687,100002,6158907,Closed,currency 1,-1121,0,-911.0,-911.0,3321.000,0,19071.000,NaN,NaN,0.0,Consumer credit,-906,0.000
1486113,100002,6113835,Closed,currency 1,-1043,0,62.0,-967.0,0.000,0,67500.000,NaN,NaN,0.0,Credit card,-758,0.000
1337779,100002,6158903,Active,currency 1,-1042,0,780.0,NaN,NaN,0,450000.000,245781.000,0.000,0.0,Consumer credit,-7,0.000
675688,100002,6158908,Closed,currency 1,-645,0,85.0,-36.0,5043.645,0,120735.000,0.000,0.000,0.0,Consumer credit,-34,0.000
675685,100002,6158905,Closed,currency 1,-476,0,NaN,-48.0,NaN,0,0.000,0.000,NaN,0.0,Credit card,-47,NaN
675689,100002,6158909,Active,currency 1,-103,0,NaN,NaN,40.500,0,31988.565,0.000,31988.565,0.0,Credit card,-24,0.000
1024666,100003,5885877,Closed,currency 1,-2586,0,-2434.0,-2131.0,0.000,0,22248.000,0.000,0.000,0.0,Consumer credit,-2131,NaN
1024667,100003,5885878,Closed,currency 1,-1636,0,-540.0,-540.0,0.000,0,112500.000,0.000,0.000,0.0,Credit card,-540,NaN
1024668,100003,5885879,Closed,currency 1,-775,0,-420.0,-621.0,0.000,0,72652.500,0.000,0.000,0.0,Consumer credit,-550,NaN
1024669,100003,5885880,Active,currency 1,-606,0,1216.0,NaN,0.000,0,810000.000,0.000,810000.000,0.0,Credit card,-43,NaN
363104,100004,6829133,Closed,currency 1,-1326,0,-595.0,-683.0,NaN,0,94500.000,0.000,0.000,0.0,Consumer credit,-682,NaN
363105,100004,6829134,Closed,currency 1,-408,0,-382.0,-382.0,0.000,0,94537.800,0.000,0.000,0.0,Consumer credit,-382,NaN
1421814,100005,6735200,Closed,currency 1,-373,0,-128.0,-123.0,NaN,0,58500.000,0.000,0.000,0.0,Credit card,-121,0.000
1421815,100005,6735201,Active,currency 1,-137,0,1324.0,NaN,NaN,0,568800.000,543087.000,0.000,0.0,Consumer credit,-11,0.000
1421816,100005,6735202,Active,currency 1,-62,0,122.0,NaN,0.000,0,29826.000,25321.500,0.000,0.0,Consumer credit,-31,4261.500
1503966,100007,5987200,Closed,currency 1,-1149,0,-783.0,-783.0,0.000,0,146250.000,0.000,0.000,0.0,Consumer credit,-783,NaN
718761,100008,6491433,Closed,currency 1,-1097,0,-853.0,-1028.0,NaN,0,105705.000,0.000,0.000,0.0,Consumer credit,-1027,NaN
1616817,100008,6491432,Closed,currency 1,-1097,0,-792.0,-790.0,NaN,0,95134.500,0.000,0.000,0.0,Consumer credit,-790,NaN
718762,100008,6491434,Active,currency 1,-78,0,471.0,NaN,0.000,0,267606.000,240057.000,0.000,0.0,Consumer credit,-16,NaN
1279720,100009,5651005,Closed,currency 1,-2882,0,-2152.0,-2152.0,NaN,0,247500.000,NaN,NaN,0.0,Consumer credit,-2152,NaN
1279725,100009,5651011,Closed,currency 1,-2018,0,-1774.0,-1774.0,0.000,0,35770.500,0.000,0.000,0.0,Consumer credit,-1518,NaN
1279722,100009,5651007,Closed,currency 1,-1879,0,-1699.0,-986.0,NaN,0,97978.500,NaN,NaN,0.0,Consumer credit,-983,NaN
1279717,100009,5651002,Closed,currency 1,-1765,0,-1581.0,-1580.0,NaN,0,66825.000,0.000,0.000,0.0,Consumer credit,-1549,NaN
1279716,100009,5651000,Closed,currency 1,-1686,0,139.0,-819.0,NaN,0,1777500.000,0.000,0.000,0.0,Consumer credit,-591,NaN
1279726,100009,5651012,Closed,currency 1,-1609,0,-1517.0,-1517.0,0.000,0,100665.000,0.000,0.000,0.0,Consumer credit,-1517,NaN
1279714,100009,5650998,Closed,currency 1,-1428,0,-1245.0,-1244.0,NaN,0,93465.000,0.000,0.000,0.0,Consumer credit,-782,NaN
1279721,100009,5651006,Closed,currency 1,-1427,0,-1245.0,-1245.0,NaN,0,93465.000,0.000,NaN,0.0,Consumer credit,-1127,NaN
1279723,100009,5651009,Active,currency 1,-1293,0,NaN,NaN,NaN,0,187200.000,0.000,NaN,0.0,Credit card,-847,NaN
564533,100009,5651008,Closed,currency 1,-1259,0,-1080.0,-986.0,NaN,0,114799.500,NaN,NaN,0.0,Consumer credit,-983,NaN
1279715,100009,5650999,Closed,currency 1,-1241,0,-1056.0,-1055.0,NaN,0,37710.000,0.000,0.000,0.0,Consumer credit,-1055,NaN
1279727,100009,5651013,Closed,currency 1,-1133,0,-951.0,-951.0,0.000,0,83952.000,NaN,NaN,0.0,Consumer credit,-949,NaN
1279713,100009,5650997,Closed,currency 1,-782,0,1044.0,-415.0,NaN,0,351000.000,0.000,0.000,0.0,Consumer credit,-375,NaN
1279728,100009,5651014,Closed,currency 1,-727,0,-482.0,-482.0,0.000,0,110655.000,0.000,0.000,0.0,Consumer credit,-482,NaN
1279712,100009,5650996,Closed,currency 1,-684,0,-313.0,-313.0,NaN,0,61965.000,0.000,0.000,0.0,Consumer credit,-283,NaN
1279719,100009,5651004,Active,currency 1,-424,0,1402.0,NaN,NaN,0,642861.000,557959.500,0.000,0.0,Consumer credit,-27,NaN
1279724,100009,5651010,Active,currency 1,-411,0,NaN,NaN,NaN,0,360000.000,192762.000,NaN,0.0,Consumer credit,-23,NaN
1279718,100009,5651003,Active,currency 1,-239,0,-209.0,NaN,NaN,0,337500.000,326628.000,0.000,0.0,Credit card,-86,NaN
1688697,100010,5576632,Closed,currency 1,-2741,0,-928.0,-1138.0,NaN,0,315000.000,0.000,NaN,0.0,Loan for business development,-1138,NaN
1688696,100010,5576630,Active,currency 1,-1138,0,689.0,NaN,NaN,0,675000.000,348007.500,0.000,0.0,Consumer credit,-18,NaN
420732,100011,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.230,0,90744.300,0.000,0.000,0.0,Consumer credit,-2172,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1658956,456244,6643949,Closed,currency 1,-400,0,696.0,-399.0,0.000,0,0.000,0.000,0.000,0.0,Credit card,-399,0.000
1658951,456244,6643943,Active,currency 1,-399,0,697.0,NaN,NaN,0,781920.000,612180.000,NaN,0.0,Consumer credit,-15,NaN
1658936,456244,6643924,Active,currency 1,-204,0,1065.0,NaN,NaN,0,360000.000,0.000,0.000,0.0,Credit card,-12,34929.000
1291211,456246,5366285,Closed,currency 1,-2141,0,-1594.0,-1819.0,NaN,0,90000.000,0.000,0.000,0.0,Consumer credit,-537,NaN
1462190,456246,5366287,Closed,currency 1,-1788,0,38.0,-843.0,NaN,0,225000.000,0.000,0.000,0.0,Consumer credit,-537,NaN
1462189,456246,5366286,Active,currency 1,-154,0,852.0,NaN,NaN,0,67500.000,0.000,0.000,0.0,Credit card,-46,NaN
1252110,456247,6618244,Closed,currency 1,-2482,0,-2299.0,-2298.0,6538.500,0,33012.000,NaN,NaN,0.0,Consumer credit,-2295,4329.000
12925,456247,6022150,Closed,currency 1,-2028,0,-1937.0,-2000.0,NaN,0,59850.000,0.000,0.000,0.0,Consumer credit,-1710,0.000
1553448,456247,6618241,Closed,currency 1,-1757,0,-1402.0,-1402.0,NaN,0,143667.000,NaN,NaN,0.0,Consumer credit,-1402,4329.000
12931,456247,6022156,Closed,currency 1,-1583,0,-852.0,-1180.0,0.000,0,292500.000,NaN,NaN,0.0,Consumer credit,-1180,NaN
12930,456247,6022155,Closed,currency 1,-832,0,-806.0,-806.0,0.000,0,101250.000,0.000,0.000,0.0,Consumer credit,-806,NaN
1252109,456247,6618243,Closed,currency 1,-776,0,-411.0,-502.0,0.000,0,169159.500,0.000,0.000,0.0,Consumer credit,-500,4329.000
12926,456247,6022151,Active,currency 1,-712,0,10253.0,NaN,NaN,0,3118500.000,2193390.000,0.000,0.0,Mortgage,-28,NaN
12929,456247,6022154,Closed,currency 1,-369,0,1458.0,-302.0,0.000,0,225000.000,NaN,NaN,0.0,Consumer credit,-302,26275.500
1252108,456247,6618242,Active,currency 1,-340,0,10617.0,NaN,2898.000,0,94500.000,NaN,NaN,0.0,Credit card,-12,0.000
12928,456247,6022153,Active,currency 1,-309,0,1517.0,NaN,22027.500,0,900000.000,0.000,0.000,0.0,Consumer credit,-32,4329.000
12927,456247,6022152,Closed,currency 1,-287,0,-190.0,-190.0,15997.410,1,48024.000,0.000,0.000,0.0,Consumer credit,-190,NaN
1534300,456249,5371694,Closed,currency 1,-2713,0,-2499.0,-2525.0,11790.000,0,64395.000,0.000,0.000,0.0,Consumer credit,-2498,NaN
1534301,456249,5371695,Active,currency 1,-2612,0,-1497.0,-1318.0,0.000,0,225000.000,0.000,0.000,0.0,Credit card,-1213,NaN
1534302,456249,5371697,Closed,currency 1,-2050,0,-1960.0,-1954.0,NaN,0,43447.500,0.000,0.000,0.0,Consumer credit,-770,NaN
1534304,456249,5371699,Closed,currency 1,-2049,0,-1960.0,-1960.0,NaN,0,43447.500,0.000,NaN,0.0,Consumer credit,-1765,NaN
1534303,456249,5371698,Closed,currency 1,-1912,0,-1727.0,-1709.0,NaN,0,248692.500,0.000,0.000,0.0,Consumer credit,-779,NaN
776766,456249,5371700,Closed,currency 1,-1911,0,-1727.0,-1740.0,NaN,0,248692.500,0.000,NaN,0.0,Consumer credit,-1723,NaN
1534307,456249,5371705,Closed,currency 1,-1680,0,NaN,-291.0,0.000,0,315000.000,0.000,0.000,0.0,Credit card,-208,NaN
776767,456249,5371701,Closed,currency 1,-1490,0,-1125.0,-1165.0,NaN,0,450000.000,NaN,NaN,0.0,Consumer credit,-1165,NaN
776765,456249,5371696,Closed,currency 1,-1454,0,-1181.0,-1240.0,18945.000,0,120183.660,0.000,0.000,0.0,Consumer credit,-1240,NaN
776768,456249,5371702,Closed,currency 1,-1250,0,-914.0,-914.0,NaN,0,540000.000,NaN,NaN,0.0,Consumer credit,-909,NaN
1534305,456249,5371703,Closed,currency 1,-1165,0,-903.0,-903.0,NaN,0,450000.000,NaN,NaN,0.0,Consumer credit,-900,NaN
1534308,456249,5371706,Closed,currency 1,-903,0,-658.0,-658.0,0.000,0,765000.000,0.000,0.000,0.0,Another type of loan,-657,NaN
1534306,456249,5371704,Active,currency 1,-483,0,1363.0,NaN,NaN,0,180000.000,163071.000,NaN,0.0,Credit card,-12,NaN
1263016,456250,6817236,Closed,currency 1,-1002,0,-272.0,-760.0,NaN,0,483349.500,0.000,0.000,0.0,Consumer credit,-127,384147.000
1263018,456250,6817238,Active,currency 1,-824,0,2340.0,NaN,0.000,0,450000.000,391731.615,58268.385,0.0,Credit card,-31,27757.395
1263017,456250,6817237,Active,currency 1,-760,0,1797.0,NaN,0.000,0,2153110.050,1840308.480,0.000,0.0,Consumer credit,-23,51799.500
312586,456253,6098498,Closed,currency 1,-919,0,-189.0,-794.0,NaN,0,675000.000,0.000,0.000,0.0,Consumer credit,-128,58369.500
312587,456253,6098499,Closed,currency 1,-919,0,-189.0,-794.0,NaN,0,675000.000,0.000,0.000,0.0,Consumer credit,-701,58369.500
479582,456253,5113039,Active,currency 1,-919,0,387.0,NaN,NaN,0,360000.000,171036.000,0.000,0.0,Credit card,-179,58369.500
639151,456253,6230038,Active,currency 1,-713,0,1113.0,NaN,NaN,0,2250000.000,1624797.000,0.000,0.0,Consumer credit,-5,NaN
1578578,456254,6669849,Closed,currency 1,-1104,0,-859.0,-859.0,NaN,0,45000.000,0.000,NaN,0.0,Consumer credit,-401,0.000
1010012,456255,5126336,Closed,currency 1,-2337,0,8620.0,-779.0,2646.000,1,38925.000,NaN,NaN,0.0,Credit card,-779,3244.500
1010013,456255,5126337,Closed,currency 1,-2337,0,-1243.0,-1621.0,16618.500,0,450000.000,NaN,NaN,0.0,Consumer credit,-1621,0.000
1010011,456255,5126335,Closed,currency 1,-1512,0,315.0,-781.0,25578.000,0,900000.000,NaN,NaN,0.0,Consumer credit,-781,0.000
1010003,456255,5126327,Closed,currency 1,-1022,0,-959.0,-958.0,NaN,0,22995.000,0.000,0.000,0.0,Consumer credit,-890,0.000
1010006,456255,5126330,Closed,currency 1,-1021,0,-959.0,-959.0,NaN,0,22995.000,0.000,NaN,0.0,Consumer credit,-953,3244.500
1010007,456255,5126331,Active,currency 1,-1020,0,806.0,NaN,NaN,0,810000.000,595102.500,NaN,0.0,Consumer credit,-8,0.000
1010004,456255,5126328,Closed,currency 1,-970,0,-621.0,-712.0,NaN,0,27472.500,0.000,0.000,0.0,Consumer credit,-700,NaN
1010005,456255,5126329,Active,currency 1,-573,0,523.0,NaN,NaN,0,553500.000,324171.000,0.000,0.0,Consumer credit,-19,0.000
1010010,456255,5126334,Active,currency 1,-451,0,279.0,NaN,15439.905,0,450000.000,191005.470,0.000,0.0,Consumer credit,-55,3244.500
1010008,456255,5126332,Active,currency 1,-378,0,27320.0,NaN,NaN,0,90000.000,61060.500,NaN,0.0,Credit card,-11,NaN
1010009,456255,5126333,Active,currency 1,-363,0,1463.0,NaN,0.000,0,436032.000,363573.540,0.000,0.0,Consumer credit,-25,0.000