In [1]:
import pandas as pd
import numpy as np
from glob import glob
from IPython.display import display
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 99)
import EDA
import utils
#sorted(glob('../data/*'))

In [2]:
df = utils.read_pickles('../data/previous_application').sort_values(['SK_ID_CURR', 'DAYS_DECISION'], ascending=[True, False])
df.head()

100%|██████████| 20/20 [00:04<00:00,  4.45it/s]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.5,23787.0,2520.0,24835.5,FRIDAY,13,1,1,0.104326,NaN,NaN,XAP,Approved,-1740,Cash through the bank,XAP,Family,Refreshed,Mobile,POS,XNA,Country-wide,23,Connectivity,8.0,high,POS mobile with interest,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,1,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,1,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,1,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
1223745,2396755,100003,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,1,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0

In [3]:
EDA.df_info(df)

Shape: (1670214, 37)

,DataType,#Nulls,#Uniques,Min,Mean,Max,Std,top10 val,top10 cnt
SK_ID_PREV,int64,0,1670214,1.000001e+06,1.923089e+06,2845382.000,532597.958696,"[1000983, 2428426, 1026910, 1024863, 2448896, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
SK_ID_CURR,int64,0,338857,1.000010e+05,2.783572e+05,456255.000,102814.823849,"[187868, 265681, 173680, 242412, 206783, 15636...","[77, 73, 72, 68, 67, 66, 64, 64, 63, 62]"
NAME_CONTRACT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Cash loans', 'Consumer loans', 'Revolving lo...","[747553, 729151, 193164, 346]"
AMT_ANNUITY,float64,372235,357959,0.000000e+00,1.595512e+04,418058.145,14782.137335,"[2250.0, 11250.0, 6750.0, 9000.0, 22500.0, 450...","[31865, 13974, 13442, 12496, 11903, 10597, 717..."
AMT_APPLICATION,float64,0,93885,0.000000e+00,1.752339e+05,6905160.000,292779.762387,"[0.0, 45000.0, 225000.0, 135000.0, 450000.0, 9...","[392402, 47831, 43543, 40678, 38905, 29367, 24..."
AMT_CREDIT,float64,1,86803,0.000000e+00,1.961140e+05,6905160.000,318574.616546,"[0.0, 45000.0, 225000.0, 450000.0, 135000.0, 1...","[336768, 35051, 21094, 19954, 18720, 17085, 13..."
AMT_DOWN_PAYMENT,float64,895844,29278,-9.000000e-01,6.697402e+03,3060045.000,20921.495410,"[0.0, 4500.0, 9000.0, 13500.0, 22500.0, 6750.0...","[369854, 21241, 14747, 9655, 8165, 7709, 6241,..."
AMT_GOODS_PRICE,float64,385515,93885,0.000000e+00,2.278473e+05,6905160.000,315396.557937,"[45000.0, 225000.0, 135000.0, 450000.0, 90000....","[47831, 43549, 40666, 38926, 29367, 24736, 205..."
WEEKDAY_APPR_PROCESS_START,object,0,7,NaN,NaN,NaN,NaN,"['TUESDAY', 'WEDNESDAY', 'MONDAY', 'FRIDAY', '...","[255118, 255010, 253557, 252048, 249099, 24063..."
HOUR_APPR_PROCESS_START,int64,0,24,0.000000e+00,1.248418e+01,23.000,3.334028,"[11, 12, 10, 13, 14, 15, 9, 16, 17, 8]","[192728, 185980, 181690, 172256, 157711, 14296..."
FLAG_LAST_APPL_PER_CONTRACT,int64,0,2,0.000000e+00,9.949258e-01,1.000,0.071052,"[1, 0]","[1661739, 8475]"
NFLAG_LAST_APPL_IN_DAY,int64,0,2,0.000000e+00,9.964675e-01,1.000,0.059330,"[1, 0]","[1664314, 5900]"
RATE_DOWN_PAYMENT,float64,895844,207033,-1.497876e-05,7.963682e-02,1.000,0.107823,"[0.0, 0.1089090909090909, 0.2178181818181818, ...","[369854, 36341, 6482, 1081, 746, 449, 304, 258..."
RATE_INTEREST_PRIMARY,float64,1664263,148,3.478125e-02,1.883569e-01,1.000,0.087671,"[0.1891363481808909, 0.14244021307945146, 0.16...","[1218, 951, 821, 681, 573, 241, 210, 204, 187,..."
RATE_INTEREST_PRIVILEGED,float64,1664263,25,3.731501e-01,7.735025e-01,1.000,0.100879,"[0.8350951374207188, 0.715644820295983, 0.6379...","[1717, 1046, 1039, 931, 876, 127, 66, 45, 40, 19]"
NAME_CASH_LOAN_PURPOSE,object,0,25,NaN,NaN,NaN,NaN,"['XAP', 'XNA', 'Repairs', 'Other', 'Urgent nee...","[922661, 677918, 23765, 15608, 8412, 2888, 269..."
NAME_CONTRACT_STATUS,object,0,4,NaN,NaN,NaN,NaN,"['Approved', 'Canceled', 'Refused', 'Unused of...","[1036781, 316319, 290678, 26436]"
DAYS_DECISION,int64,0,2922,-2.922000e+03,-8.806797e+02,-1.000,779.099667,"[-245, -238, -210, -273, -196, -224, -252, -18...","[2444, 2390, 2375, 2350, 2315, 2305, 2300, 228..."
NAME_PAYMENT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Cash through the bank', 'XNA', 'Non-cash fro...","[1033552, 627384, 8193, 1085]"
CODE_REJECT_REASON,object,0,9,NaN,NaN,NaN,NaN,"['XAP', 'HC', 'LIMIT', 'SCO', 'CLIENT', 'SCOFR...","[1353093, 175231, 55680, 37467, 26436, 12811, ..."
NAME_TYPE_SUITE,object,820405,7,NaN,NaN,NaN,NaN,"['Unaccompanied', 'Family', 'Spouse, partner',...","[508970, 213263, 67069, 31566, 17624, 9077, 2240]"
NAME_CLIENT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Repeater', 'New', 'Refreshed', 'XNA']","[1231261, 301363, 135649, 1941]"
NAME_GOODS_CATEGORY,object,0,28,NaN,NaN,NaN,NaN,"['XNA', 'Mobile', 'Consumer Electronics', 'Com...","[950809, 224708, 121576, 105769, 99441, 53656,..."
NAME_PORTFOLIO,object,0,5,NaN,NaN,NaN,NaN,"['POS', 'Cash', 'XNA', 'Cards', 'Cars']","[691011, 461563, 372230, 144985, 425]"
NAME_PRODUCT_TYPE,object,0,3,NaN,NaN,NaN,NaN,"['XNA', 'x-sell', 'walk-in']","[1063666, 456287, 150261]"
CHANNEL_TYPE,object,0,8,NaN,NaN,NaN,NaN,"['Credit and cash offices', 'Country-wide', 'S...","[719968, 494690, 212083, 108528, 71297, 57046,..."
SELLERPLACE_AREA,int64,0,2097,-1.000000e+00,3.139511e+02,4000000.000,7127.443459,"[-1, 0, 50, 30, 20, 100, 40, 25, 15, 150]","[762675, 60523, 37401, 34423, 33840, 31409, 24..."
NAME_SELLER_INDUSTRY,object,0,11,NaN,NaN,NaN,NaN,"['XNA', 'Consumer electronics', 'Connectivity'...","[855720, 398265, 276029, 57849, 29781, 23949, ..."
CNT_PAYMENT,float64,372230,49,0.000000e+00,1.605408e+01,84.000,14.567288,"[12.0, 6.0, 0.0, 10.0, 24.0, 18.0, 36.0, 60.0,...","[323049, 190461, 144985, 141851, 137764, 77430..."
NAME_YIELD_GROUP,object,0,5,NaN,NaN,NaN,NaN,"['XNA', 'middle', 'high', 'low_normal', 'low_a...","[517215, 385532, 353331, 322095, 92041]"
PRODUCT_COMBINATION,object,346,17,NaN,NaN,NaN,NaN,"['Cash', 'POS household with interest', 'POS m...","[285990, 263622, 220670, 143883, 130248, 11258..."
DAYS_FIRST_DRAWING,float64,673065,2838,-2.922000e+03,3.422099e+05,365243.000,88916.115834,"[365243.0, -228.0, -224.0, -212.0, -223.0, -22...","[934444, 123, 121, 121, 119, 118, 117, 117, 11..."
DAYS_FIRST_DUE,float64,673065,2892,-2.892000e+03,1.382627e+04,365243.000,72444.869708,"[365243.0, -334.0, -509.0, -208.0, -330.0, -29...","[40645, 772, 760, 751, 750, 746, 745, 744, 744..."
DAYS_LAST_DUE_1ST_VERSION,float64,673065,4605,-2.801000e+03,3.376777e+04,365243.000,106857.034789,"[365243.0, 9.0, 8.0, 0.0, 5.0, 10.0, 2.0, 1.0,...","[93864, 720, 706, 705, 702, 698, 688, 685, 685..."
DAYS_LAST_DUE,float64,673065,2873,-2.889000e+03,7.658240e+04,365243.000,149647.415123,"[365243.0, -245.0, -188.0, -239.0, -167.0, -24...","[211221, 658, 650, 642, 638, 629, 627, 624, 62..."
DAYS_TERMINATION,float64,673065,2830,-2.874000e+03,8.199234e+04,365243.000,153303.516729,"[365243.0, -233.0, -170.0, -184.0, -163.0, -16...","[225913, 786, 770, 770, 769, 760, 754, 753, 74..."
NFLAG_INSURED_ON_APPROVAL,float64,673065,2,0.000000e+00,3.325702e-01,1.000,0.471134,"[0.0, 1.0]","[665527, 331622]"

In [3]:
ids = df.SK_ID_CURR.unique()

In [4]:
tmp = df[df.SK_ID_CURR==np.random.choice(ids)]
tmp

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
365920,1299385,233573,Revolving loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,9,1,1,NaN,NaN,NaN,XAP,Canceled,-116,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1204654,2301069,233573,Consumer loans,6424.875,78070.5,90436.5,0.0,78070.5,SATURDAY,10,1,1,0.0,NaN,NaN,XAP,Approved,-273,Cash through the bank,XAP,Unaccompanied,New,Consumer Electronics,POS,XNA,Country-wide,2661,Consumer electronics,18.0,low_normal,POS household with interest,365243.0,-243.0,267.0,365243.0,365243.0,1.0

In [5]:
tmp = df[df.SK_ID_CURR.isin(np.random.choice(ids, size=9))]
tmp

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
71327,2816415,140172,Revolving loans,NaN,0.00,0.0,NaN,NaN,MONDAY,15,1,1,NaN,NaN,NaN,XAP,Canceled,-323,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
1077305,2844537,140172,Cash loans,NaN,0.00,0.0,NaN,NaN,MONDAY,16,1,1,NaN,NaN,NaN,XNA,Canceled,-323,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1095636,2071065,140172,Revolving loans,10125.000,202500.00,202500.0,NaN,202500.00,MONDAY,15,1,1,NaN,NaN,NaN,XAP,Approved,-323,XNA,XAP,Unaccompanied,Repeater,XNA,Cards,x-sell,Credit and cash offices,-1,XNA,0.0,XNA,Card X-Sell,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
559891,1887759,140172,Consumer loans,7936.200,94500.00,83583.0,18900.00,94500.00,TUESDAY,13,1,1,0.200851,NaN,NaN,XAP,Approved,-392,XNA,XAP,NaN,Refreshed,Homewares,POS,XNA,Stone,30,Construction,12.0,low_normal,POS industry with interest,365243.0,-333.0,-3.0,-303.0,-296.0,0.0
1411986,2565884,140172,Consumer loans,13712.940,117000.00,113989.5,11700.00,117000.00,FRIDAY,11,1,1,0.101380,NaN,NaN,XAP,Approved,-2314,Cash through the bank,XAP,Other_B,New,Computers,POS,XNA,Stone,57,Consumer electronics,10.0,middle,POS household with interest,365243.0,-2279.0,-2009.0,-2129.0,-2123.0,0.0
623924,1201303,144977,Consumer loans,4070.880,25605.00,32404.5,0.00,25605.00,FRIDAY,10,1,1,0.000000,NaN,NaN,XAP,Approved,-1830,Cash through the bank,XAP,Family,Repeater,Audio/Video,POS,XNA,Country-wide,32,Connectivity,12.0,high,POS mobile with interest,365243.0,-1799.0,-1469.0,-1499.0,-1492.0,0.0
865889,1890382,144977,Consumer loans,4324.275,22810.50,21546.0,2281.50,22810.50,FRIDAY,16,1,1,0.104281,NaN,NaN,XAP,Approved,-2460,Cash through the bank,XAP,Children,Repeater,Mobile,POS,XNA,Country-wide,32,Connectivity,6.0,low_normal,POS mobile with interest,365243.0,-2429.0,-2279.0,-2279.0,-2269.0,1.0
74706,1591892,174025,Revolving loans,2250.000,45000.00,45000.0,NaN,45000.00,THURSDAY,15,1,1,NaN,NaN,NaN,XAP,Approved,-232,XNA,XAP,Unaccompanied,New,XNA,Cards,walk-in,Credit and cash offices,-1,XNA,0.0,XNA,Card Street,-232.0,-190.0,365243.0,365243.0,365243.0,0.0
605851,1124055,174025,Revolving loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,1,1,NaN,NaN,NaN,XAP,Canceled,-232,XNA,XAP,NaN,New,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
678277,1593325,278032,Revolving loans,6750.000,135000.00,135000.0,NaN,135000.00,SATURDAY,13,1,1,NaN,NaN,NaN,XAP,Approved,-178,XNA,XAP,Unaccompanied,Repeater,XNA,Cards,x-sell,AP+ (Cash loan),100,XNA,0.0,XNA,Card X-Sell,-178.0,-137.0,365243.0,365243.0,365243.0,0.0
949385,1821662,278032,Consumer loans,4199.895,44995.50,44995.5,0.00,44995.50,FRIDAY,11,1,1,0.000000,NaN,NaN,XAP,Approved,-326,Cash through the bank,XAP,Unaccompanied,Repeater,Consumer Electronics,POS,XNA,Stone,62,Consumer electronics,12.0,low_normal,POS household with interest,365243.0,-295.0,35.0,-175.0,-170.0,0.0
1181779,2134576,278032,Consumer loans,6155.100,31495.50,33160.5,0.00,31495.50,TUESDAY,14,1,1,0.000000,NaN,NaN,XAP,Approved,-588,Cash through the bank,XAP,NaN,New,Consumer Electronics,POS,XNA,Stone,62,Consumer electronics,6.0,middle,POS household with interest,365243.0,-557.0,-407.0,-407.0,-401.0,0.0
1247900,1623417,291356,Consumer loans,10332.000,157500.00,157500.0,0.00,157500.00,WEDNESDAY,11,1,1,0.000000,NaN,NaN,XAP,Approved,-861,Cash through the bank,XAP,NaN,New,Construction Materials,POS,XNA,Stone,30,Construction,18.0,low_normal,POS industry with interest,365243.0,-824.0,-314.0,-314.0,-297.0,0.0
663844,2800901,341498,Consumer loans,16766.280,150475.50,166365.0,0.00,150475.50,THURSDAY,10,1,1,0.000000,NaN,NaN,XAP,Approved,-57,XNA,XAP,"Spouse, partner",Repeater,Furniture,POS,XNA,Regional / Local,2000,Furniture,12.0,middle,POS industry with interest,365243.0,-26.0,304.0,365243.0,365243.0,0.0
799358,2093153,341498,Cash loans,NaN,0.00,0.0,NaN,NaN,FRIDAY,5,1,1,NaN,NaN,NaN,XNA,Canceled,-280,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
674911,2640005,341498,Consumer loans,38690.190,348372.00,367533.0,0.00,348372.00,FRIDAY,8,1,1,0.000000,NaN,NaN,XAP,Approved,-448,XNA,XAP,NaN,Repeater,Furniture,POS,XNA,Regional / Local,2000,Furniture,10.0,low_action,POS industry without interest,365243.0,-415.0,-145.0,-145.0,-138.0,0.0
1068472,2463494,341498,Consumer loans,18584.010,359667.00,359667.0,0.00,359667.00,WEDNESDAY,5,1,1,0.000000,NaN,NaN,XAP,Approved,-667,XNA,XAP,NaN,New,Homewares,POS,XNA,Country-wide,79,Construction,24.0,low_normal,POS other with interest,365243.0,-636.0,54.0,365243.0,365243.0,0.0
1432321,1315049,391217,Consumer loans,7069.140,57586.50,51826.5,5760.00,57586.50,TUESDAY,14,1,1,0.108935,NaN,NaN,XAP,Approved,-1546,Cash through the bank,XAP,Family,Repeater,Mobile,POS,XNA,Regional / Local,15,Connectivity,10.0,high,POS mobile with interest,365243.0,-1508.0,-1238.0,-1238.0,365243.0,0.0
707266,1059740,391217,Consumer loans,11720.250,104400.00,97425.0,14400.00,104400.00,TUESDAY,10,1,1,0.140245,NaN,NaN,XAP,Approved,-1980,XNA,XAP,NaN,Repeater,Computers,POS,XNA,Stone,30,Consumer electronics,10.0,middle,POS household with interest,365243.0,-1947.0,-1677.0,-1677.0,-1667.0,0.0
742222,1371023,391217,Consumer loans,11300.355,104400.00,101713.5,10440.00,104400.00,TUESDAY,10,1,1,0.101380,NaN,NaN,XAP,Refused,-1980,XNA,LIMIT,NaN,Repeater,Computers,POS,XNA,Stone,30,Consumer electronics,10.0,low_normal,POS household with interest,NaN,NaN,NaN,NaN,NaN,NaN
1160649,2478651,397461,Cash loans,19911.150,454500.00,519313.5,NaN,454500.00,SATURDAY,9,1,1,NaN,NaN,NaN,XNA,Approved,-331,Cash through the bank,XAP,Family,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,36.0,low_normal,Cash X-Sell: low,365243.0,-301.0,749.0,365243.0,365243.0,1.0
1429572,1733516,397461,Cash loans,NaN,0.00,0.0,NaN,NaN,SATURDAY,8,1,1,NaN,NaN,NaN,XNA,Canceled,-331,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1160648,1073522,397461,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,14,1,1,NaN,NaN,NaN,XNA,Canceled,-333,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
14881,1895659,397461,Consumer loans,9312.615,122625.00,142047.0,0.00,122625.00,SUNDAY,12,1,1,0.000000,NaN,NaN,XAP,Approved,-834,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,8,Furniture,18.0,low_normal,POS industry with interest,365243.0,-802.0,-292.0,-292.0,-288.0,0.0
722056,1338108,397461,Consumer loans,3754.485,34137.00,33763.5,3415.50,34137.00,TUESDAY,10,1,1,0.100051,NaN,NaN,XAP,Approved,-2687,XNA,XAP,Family,New,Mobile,POS,XNA,Country-wide,38,Connectivity,12.0,high,POS mobile with interest,365243.0,-2656.0,-2326.0,-2326.0,-2318.0,1.0
566689,2754514,428606,Consumer loans,6717.015,69880.50,37012.5,34942.50,69880.50,SATURDAY,14,1,1,0.528880,NaN,NaN,XAP,Approved,-116,Cash through the bank,XAP,Unaccompanied,Repeater,Consumer Electronics,POS,XNA,Country-wide,1000,Consumer electronics,6.0,low_normal,POS household with interest,365243.0,-86.0,64.0,365243.0,365243.0,1.0
1035887,2176783,428606,Revolving loans,2250.000,45000.00,45000.0,NaN,45000.00,SATURDAY,14,1,1,NaN,NaN,NaN,XAP,Refused,-116,XNA,SCO,Unaccompanied,Repeater,XNA,Cards,walk-in,Country-wide,1000,Consumer electronics,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN
736861,1143888,428606,Consumer loans,18989.010,189875.34,170887.5,18987.84,189875.34,WEDNESDAY,12,1,1,0.108911,NaN,NaN,XAP,Approved,-553,Cash through the bank,XAP,NaN,Refreshed,Construction Materials,POS,XNA,Stone,18,Construction,10.0,low_normal,POS industry with interest,365243.0,-521.0,-251.0,-251.0,-248.0,0.0
1665832,1600402,428606,Consumer loans,17782.335,103500.00,93150.0,10350.00,103500.00,SUNDAY,12,1,1,0.108909,NaN,NaN,XAP,Approved,-1928,Cash through the bank,XAP,Unaccompanied,Refreshed,Clothing and Accessories,POS,XNA,Stone,108,Clothing,6.0,middle,POS industry with interest,365243.0,-1897.0,-1747.0,-1807.0,-1802.0,0.0

In [6]:
tmp.to_csv('sample_pre.csv', index=False)

In [3]:
imp = pd.read_csv('LOG/imp_199_cv_filter.py.csv')

In [4]:
imp

                                                   index  split         gain
0          prev_NAME_YIELD_GROUP_DAYS_DECISION-high_mean     85  4567.900959
1                 prev_NAME_CONTRACT_STATUS_Refused_norm     83  4170.988615
2      prev_NAME_YIELD_GROUP_DAYS_LAST_DUE_1ST_VERSIO...     78  4084.240275
3                          prev_DL1-0PRODUCT_COMBINATION     73  3992.978409
4      prev_NAME_CONTRACT_STATUS_DAYS_DECISION-Refuse...     66  3476.701177
5      prev_NAME_YIELD_GROUP_DAYS_LAST_DUE_1ST_VERSIO...     74  3291.238058
6      prev_PRODUCT_COMBINATION_CNT_PAYMENT-Cash-X-Se...     84  2928.021604
7      prev_gby-SK_ID_CURR-CODE_REJECT_REASON_AMT_DOW...     45  2593.869161
8      prev_gby-SK_ID_CURR-CODE_REJECT_REASON_DAYS_FI...     35  2462.419233
9            prev_NAME_YIELD_GROUP_CNT_PAYMENT-high_mean     83  2416.010844
10                      prev_CODE_REJECT_REASON_XAP_norm     63  2413.962090
11            prev_NAME_YIELD_GROUP_CNT_PAYMENT-high_sum    111  2406.003189
12     prev_PRODUCT_COMBINATION_DAYS_LAST_DUE_1ST_VER...     70  2374.205954
13     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_DAYS_LA...     34  2204.794252
14     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_DAYS_DE...     59  1932.649053
15        prev_NAME_CLIENT_TYPE_AMT_DOWN_PAYMENT-New_sum     70  1904.059055
16            prev_NAME_CLIENT_TYPE_AMT_ANNUITY-New_mean     93  1785.998265
17         prev_NAME_YIELD_GROUP_CNT_PAYMENT-middle_mean    102  1737.908010
18             prev_NAME_CLIENT_TYPE_AMT_ANNUITY-New_sum    106  1730.882964
19     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_AMT_ANN...     62  1653.308697
20     prev_NAME_PRODUCT_TYPE_DAYS_DECISION-walk-in_mean     34  1637.180585
21                            prev_DL1-0NAME_YIELD_GROUP     25  1592.917909
22     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_DAYS_LA...     38  1572.202748
23             prev_NAME_YIELD_GROUP_AMT_CREDIT-high_sum     84  1520.659127
24       prev_NAME_CLIENT_TYPE_RATE_DOWN_PAYMENT-New_sum     74  1474.673487
25           prev_CODE_REJECT_REASON_AMT_ANNUITY-XAP_sum     72  1468.174098
26     prev_NAME_CONTRACT_STATUS_AMT_ANNUITY-Approved...     66  1460.728587
27     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_AMT_DOW...     38  1360.892509
28     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_AMT_DOW...     32  1314.356559
29     prev_NAME_CLIENT_TYPE_HOUR_APPR_PROCESS_START-...     71  1312.463737
30         prev_NAME_CLIENT_TYPE_AMT_APPLICATION-New_sum     83  1302.630826
31     prev_NAME_CONTRACT_STATUS_DAYS_DECISION-Refuse...     47  1298.506882
32                               prev_DL1-0DAYS_LAST_DUE     89  1291.242340
33       prev_NAME_YIELD_GROUP_AMT_DOWN_PAYMENT-high_sum     61  1273.801632
34         prev_NAME_YIELD_GROUP_DAYS_LAST_DUE-high_mean     69  1269.229432
35              prev_NAME_CLIENT_TYPE_AMT_CREDIT-New_sum     89  1262.690366
36          prev_NAME_YIELD_GROUP_DAYS_LAST_DUE-high_sum     49  1245.777441
37        prev_NAME_CLIENT_TYPE_DAYS_TERMINATION-New_sum     51  1220.704210
38        prev_NAME_CLIENT_TYPE_AMT_GOODS_PRICE-New_mean     76  1209.859891
39     prev_active_gby-SK_ID_CURR_DAYS_LAST_DUE_1ST_V...     76  1205.678130
40      prev_NAME_CONTRACT_STATUS_AMT_CREDIT-Refused_std     49  1204.452845
41       prev_NAME_YIELD_GROUP_DAYS_TERMINATION-high_sum     51  1189.027791
42      prev_NAME_YIELD_GROUP_DAYS_TERMINATION-high_mean     65  1176.233049
43      prev_CODE_REJECT_REASON_DAYS_DECISION-SCOFR_mean     53  1161.688549
44           prev_NAME_CLIENT_TYPE_DAYS_DECISION-New_sum     67  1157.527945
45                                  prev_DL1-1SK_ID_PREV     91  1149.655390
46     prev_NAME_CONTRACT_TYPE_DAYS_FIRST_DUE-Revolvi...     42  1139.013722
47     prev_PRODUCT_COMBINATION_CNT_PAYMENT-Cash-X-Se...     56  1138.099397
48     prev_gby-SK_ID_CURR-CODE_REJECT_REASON_RATE_DO...     33  1137.009599
...                                                  ...    ...          ...
17765        prev_NAME_PORTFOLIO_DAYS_DECISION-Cars_mean      0     0.000000
17766  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17767  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17768  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17769          prev_NAME_PORTFOLIO_CNT_PAYMENT-Cars_mean      0     0.000000
17770         prev_NAME_PORTFOLIO_CNT_PAYMENT-Cards_mean      0     0.000000
17771      prev_NAME_PORTFOLIO_AMT_GOODS_PRICE-Cars_mean      0     0.000000
17772  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_CNT_P...      0     0.000000
17773      prev_NAME_PORTFOLIO_AMT_DOWN_PAYMENT-XNA_mean      0     0.000000
17774     prev_NAME_PORTFOLIO_AMT_DOWN_PAYMENT-Cash_mean      0     0.000000
17775     prev_NAME_PORTFOLIO_AMT_DOWN_PAYMENT-Cars_mean      0     0.000000
17776  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_CNT_P...      0     0.000000
17777           prev_NAME_PORTFOLIO_AMT_CREDIT-Cars_mean      0     0.000000
17778  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_DAYS_...      0     0.000000
17779  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_DAYS_...      0     0.000000
17780      prev_NAME_PORTFOLIO_AMT_APPLICATION-Cars_mean      0     0.000000
17781  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_DAYS_...      0     0.000000
17782  prev_NAME_PORTFOLIO_DAYS_LAST_DUE_1ST_VERSION-...      0     0.000000
17783  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17784     prev_NAME_PORTFOLIO_DAYS_TERMINATION-Cars_mean      0     0.000000
17785  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17786  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17787       prev_NAME_PORTFOLIO_AMT_APPLICATION-Cars_sum      0     0.000000
17788  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17789            prev_NAME_PORTFOLIO_AMT_ANNUITY-XNA_sum      0     0.000000
17790  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17791           prev_NAME_PORTFOLIO_AMT_ANNUITY-Cars_sum      0     0.000000
17792  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17793  prev_NAME_PORTFOLIO_RATE_INTEREST_PRIVILEGED-P...      0     0.000000
17794  prev_NAME_PORTFOLIO_RATE_INTEREST_PRIMARY-POS_...      0     0.000000
17795     prev_NAME_PORTFOLIO_RATE_DOWN_PAYMENT-XNA_mean      0     0.000000
17796  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17797    prev_NAME_PORTFOLIO_RATE_DOWN_PAYMENT-Cash_mean      0     0.000000
17798    prev_NAME_PORTFOLIO_RATE_DOWN_PAYMENT-Cars_mean      0     0.000000
17799  prev_NAME_PORTFOLIO_NFLAG_LAST_APPL_IN_DAY-XNA...      0     0.000000
17800  prev_NAME_PORTFOLIO_NFLAG_LAST_APPL_IN_DAY-POS...      0     0.000000
17801  prev_NAME_PORTFOLIO_NFLAG_LAST_APPL_IN_DAY-Car...      0     0.000000
17802  prev_NAME_PORTFOLIO_NFLAG_INSURED_ON_APPROVAL-...      0     0.000000
17803  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17804  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17805  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17806  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17807  prev_NAME_PORTFOLIO_FLAG_LAST_APPL_PER_CONTRAC...      0     0.000000
17808  prev_NAME_PORTFOLIO_FLAG_LAST_APPL_PER_CONTRAC...      0     0.000000
17809  prev_NAME_PORTFOLIO_FLAG_LAST_APPL_PER_CONTRAC...      0     0.000000
17810  prev_NAME_PORTFOLIO_FLAG_LAST_APPL_PER_CONTRAC...      0     0.000000
17811  prev_NAME_PORTFOLIO_FLAG_LAST_APPL_PER_CONTRAC...      0     0.000000
17812  prev_gby-SK_ID_CURR-NAME_CONTRACT_STATUS_RATE_...      0     0.000000
17813  prev_WEEKDAY_APPR_PROCESS_START_RATE_INTEREST_...      0     0.000000

[17814 rows x 3 columns]