In [1]:
import pandas as pd
import numpy as np
from glob import glob
from IPython.display import display
pd.set_option('display.max_columns', 99)
pd.set_option('display.max_rows', 99)
import EDA
import utils
sorted(glob('../data/*'))

['../data/101_test',
 '../data/101_train',
 '../data/102_CHANNEL_TYPE_test',
 '../data/102_CHANNEL_TYPE_test_filtered',
 '../data/102_CHANNEL_TYPE_train',
 '../data/102_CHANNEL_TYPE_train_filtered',
 '../data/102_CODE_REJECT_REASON_test',
 '../data/102_CODE_REJECT_REASON_test_filtered',
 '../data/102_CODE_REJECT_REASON_train',
 '../data/102_CODE_REJECT_REASON_train_filtered',
 '../data/102_NAME_CASH_LOAN_PURPOSE_test',
 '../data/102_NAME_CASH_LOAN_PURPOSE_test_filtered',
 '../data/102_NAME_CASH_LOAN_PURPOSE_train',
 '../data/102_NAME_CASH_LOAN_PURPOSE_train_filtered',
 '../data/102_NAME_CLIENT_TYPE_test',
 '../data/102_NAME_CLIENT_TYPE_test_filtered',
 '../data/102_NAME_CLIENT_TYPE_train',
 '../data/102_NAME_CLIENT_TYPE_train_filtered',
 '../data/102_NAME_CONTRACT_STATUS_test',
 '../data/102_NAME_CONTRACT_STATUS_test_filtered',
 '../data/102_NAME_CONTRACT_STATUS_train',
 '../data/102_NAME_CONTRACT_STATUS_train_filtered',
 '../data/102_NAME_CONTRACT_TYPE_test',
 '../data/102_NAME_CONTRACT_TYPE_test_filtered',
 '../data/102_NAME_CONTRACT_TYPE_train',
 '../data/102_NAME_CONTRACT_TYPE_train_filtered',
 '../data/102_NAME_GOODS_CATEGORY_test',
 '../data/102_NAME_GOODS_CATEGORY_test_filtered',
 '../data/102_NAME_GOODS_CATEGORY_train',
 '../data/102_NAME_GOODS_CATEGORY_train_filtered',
 '../data/102_NAME_PAYMENT_TYPE_test',
 '../data/102_NAME_PAYMENT_TYPE_test_filtered',
 '../data/102_NAME_PAYMENT_TYPE_train',
 '../data/102_NAME_PAYMENT_TYPE_train_filtered',
 '../data/102_NAME_PORTFOLIO_test',
 '../data/102_NAME_PORTFOLIO_test_filtered',
 '../data/102_NAME_PORTFOLIO_train',
 '../data/102_NAME_PORTFOLIO_train_filtered',
 '../data/102_NAME_PRODUCT_TYPE_test',
 '../data/102_NAME_PRODUCT_TYPE_test_filtered',
 '../data/102_NAME_PRODUCT_TYPE_train',
 '../data/102_NAME_PRODUCT_TYPE_train_filtered',
 '../data/102_NAME_SELLER_INDUSTRY_test',
 '../data/102_NAME_SELLER_INDUSTRY_test_filtered',
 '../data/102_NAME_SELLER_INDUSTRY_train',
 '../data/102_NAME_SELLER_INDUSTRY_train_filtered',
 '../data/102_NAME_TYPE_SUITE_test',
 '../data/102_NAME_TYPE_SUITE_test_filtered',
 '../data/102_NAME_TYPE_SUITE_train',
 '../data/102_NAME_TYPE_SUITE_train_filtered',
 '../data/102_NAME_YIELD_GROUP_test',
 '../data/102_NAME_YIELD_GROUP_test_filtered',
 '../data/102_NAME_YIELD_GROUP_train',
 '../data/102_NAME_YIELD_GROUP_train_filtered',
 '../data/102_PRODUCT_COMBINATION_test',
 '../data/102_PRODUCT_COMBINATION_test_filtered',
 '../data/102_PRODUCT_COMBINATION_train',
 '../data/102_PRODUCT_COMBINATION_train_filtered',
 '../data/102_SK_ID_PREV_test',
 '../data/102_SK_ID_PREV_test_filtered',
 '../data/102_SK_ID_PREV_train',
 '../data/102_SK_ID_PREV_train_filtered',
 '../data/102_WEEKDAY_APPR_PROCESS_START_test',
 '../data/102_WEEKDAY_APPR_PROCESS_START_test_filtered',
 '../data/102_WEEKDAY_APPR_PROCESS_START_train',
 '../data/102_WEEKDAY_APPR_PROCESS_START_train_filtered',
 '../data/102_test',
 '../data/102_test_filtered',
 '../data/102_train',
 '../data/102_train_filtered',
 '../data/103_test',
 '../data/103_test_filtered',
 '../data/103_train',
 '../data/103_train_filtered',
 '../data/104_test',
 '../data/104_test_filtered',
 '../data/104_train',
 '../data/104_train_filtered',
 '../data/105_test',
 '../data/105_test_filtered',
 '../data/105_train',
 '../data/105_train_filtered',
 '../data/106_test',
 '../data/106_test_filtered',
 '../data/106_train',
 '../data/106_train_filtered',
 '../data/107_test',
 '../data/107_test_filtered',
 '../data/107_train',
 '../data/107_train_filtered',
 '../data/108_CHANNEL_TYPE_test',
 '../data/108_CHANNEL_TYPE_test_filtered',
 '../data/108_CHANNEL_TYPE_train',
 '../data/108_CHANNEL_TYPE_train_filtered',
 '../data/108_CODE_REJECT_REASON_test',
 '../data/108_CODE_REJECT_REASON_test_filtered',
 '../data/108_CODE_REJECT_REASON_train',
 '../data/108_CODE_REJECT_REASON_train_filtered',
 '../data/108_NAME_CASH_LOAN_PURPOSE_test',
 '../data/108_NAME_CASH_LOAN_PURPOSE_test_filtered',
 '../data/108_NAME_CASH_LOAN_PURPOSE_train',
 '../data/108_NAME_CASH_LOAN_PURPOSE_train_filtered',
 '../data/108_NAME_CLIENT_TYPE_test',
 '../data/108_NAME_CLIENT_TYPE_test_filtered',
 '../data/108_NAME_CLIENT_TYPE_train',
 '../data/108_NAME_CLIENT_TYPE_train_filtered',
 '../data/108_NAME_CONTRACT_STATUS_test',
 '../data/108_NAME_CONTRACT_STATUS_test_filtered',
 '../data/108_NAME_CONTRACT_STATUS_train',
 '../data/108_NAME_CONTRACT_STATUS_train_filtered',
 '../data/108_NAME_CONTRACT_TYPE_test',
 '../data/108_NAME_CONTRACT_TYPE_test_filtered',
 '../data/108_NAME_CONTRACT_TYPE_train',
 '../data/108_NAME_CONTRACT_TYPE_train_filtered',
 '../data/108_NAME_GOODS_CATEGORY_test',
 '../data/108_NAME_GOODS_CATEGORY_test_filtered',
 '../data/108_NAME_GOODS_CATEGORY_train',
 '../data/108_NAME_GOODS_CATEGORY_train_filtered',
 '../data/108_NAME_PAYMENT_TYPE_test',
 '../data/108_NAME_PAYMENT_TYPE_test_filtered',
 '../data/108_NAME_PAYMENT_TYPE_train',
 '../data/108_NAME_PAYMENT_TYPE_train_filtered',
 '../data/108_NAME_PORTFOLIO_test',
 '../data/108_NAME_PORTFOLIO_test_filtered',
 '../data/108_NAME_PORTFOLIO_train',
 '../data/108_NAME_PORTFOLIO_train_filtered',
 '../data/108_NAME_PRODUCT_TYPE_test',
 '../data/108_NAME_PRODUCT_TYPE_test_filtered',
 '../data/108_NAME_PRODUCT_TYPE_train',
 '../data/108_NAME_PRODUCT_TYPE_train_filtered',
 '../data/108_NAME_SELLER_INDUSTRY_test',
 '../data/108_NAME_SELLER_INDUSTRY_test_filtered',
 '../data/108_NAME_SELLER_INDUSTRY_train',
 '../data/108_NAME_SELLER_INDUSTRY_train_filtered',
 '../data/108_NAME_TYPE_SUITE_test',
 '../data/108_NAME_TYPE_SUITE_test_filtered',
 '../data/108_NAME_TYPE_SUITE_train',
 '../data/108_NAME_TYPE_SUITE_train_filtered',
 '../data/108_NAME_YIELD_GROUP_test',
 '../data/108_NAME_YIELD_GROUP_test_filtered',
 '../data/108_NAME_YIELD_GROUP_train',
 '../data/108_NAME_YIELD_GROUP_train_filtered',
 '../data/108_PRODUCT_COMBINATION_test',
 '../data/108_PRODUCT_COMBINATION_test_filtered',
 '../data/108_PRODUCT_COMBINATION_train',
 '../data/108_PRODUCT_COMBINATION_train_filtered',
 '../data/108_WEEKDAY_APPR_PROCESS_START_test',
 '../data/108_WEEKDAY_APPR_PROCESS_START_test_filtered',
 '../data/108_WEEKDAY_APPR_PROCESS_START_train',
 '../data/108_WEEKDAY_APPR_PROCESS_START_train_filtered',
 '../data/109_test',
 '../data/109_test_filtered',
 '../data/109_train',
 '../data/109_train_filtered',
 '../data/110_test',
 '../data/110_test_filtered',
 '../data/110_train',
 '../data/110_train_filtered',
 '../data/POS_CASH_balance',
 '../data/bureau',
 '../data/bureau_balance',
 '../data/credit_card_balance',
 '../data/installments_payments',
 '../data/label',
 '../data/previous_application',
 '../data/sub.p',
 '../data/test',
 '../data/train']

In [2]:
df = utils.read_pickles('../data/previous_application').sort_values(['SK_ID_CURR', 'SK_ID_PREV'])
df.head()

100%|██████████| 20/20 [00:05<00:00,  3.74it/s]

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
201668,1369693,100001,Consumer loans,3951.000,24835.5,23787.0,2520.0,24835.5,FRIDAY,13,1,1,0.104326,NaN,NaN,XAP,Approved,-1740,Cash through the bank,XAP,Family,Refreshed,Mobile,POS,XNA,Country-wide,23,Connectivity,8.0,high,POS mobile with interest,365243.0,-1709.0,-1499.0,-1619.0,-1612.0,0.0
892077,1038818,100002,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,1,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
575941,1810518,100003,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,1,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
1223745,2396755,100003,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,1,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
1021650,2636178,100003,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,1,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0

In [3]:
EDA.df_info(df)

Shape: (1670214, 37)

,DataType,#Nulls,#Uniques,Min,Mean,Max,Std,top10 val,top10 cnt
SK_ID_PREV,int64,0,1670214,1.000001e+06,1.923089e+06,2845382.000,532597.958696,"[1000983, 2428426, 1026910, 1024863, 2448896, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
SK_ID_CURR,int64,0,338857,1.000010e+05,2.783572e+05,456255.000,102814.823849,"[187868, 265681, 173680, 242412, 206783, 15636...","[77, 73, 72, 68, 67, 66, 64, 64, 63, 62]"
NAME_CONTRACT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Cash loans', 'Consumer loans', 'Revolving lo...","[747553, 729151, 193164, 346]"
AMT_ANNUITY,float64,372235,357959,0.000000e+00,1.595512e+04,418058.145,14782.137335,"[2250.0, 11250.0, 6750.0, 9000.0, 22500.0, 450...","[31865, 13974, 13442, 12496, 11903, 10597, 717..."
AMT_APPLICATION,float64,0,93885,0.000000e+00,1.752339e+05,6905160.000,292779.762387,"[0.0, 45000.0, 225000.0, 135000.0, 450000.0, 9...","[392402, 47831, 43543, 40678, 38905, 29367, 24..."
AMT_CREDIT,float64,1,86803,0.000000e+00,1.961140e+05,6905160.000,318574.616546,"[0.0, 45000.0, 225000.0, 450000.0, 135000.0, 1...","[336768, 35051, 21094, 19954, 18720, 17085, 13..."
AMT_DOWN_PAYMENT,float64,895844,29278,-9.000000e-01,6.697402e+03,3060045.000,20921.495410,"[0.0, 4500.0, 9000.0, 13500.0, 22500.0, 6750.0...","[369854, 21241, 14747, 9655, 8165, 7709, 6241,..."
AMT_GOODS_PRICE,float64,385515,93885,0.000000e+00,2.278473e+05,6905160.000,315396.557937,"[45000.0, 225000.0, 135000.0, 450000.0, 90000....","[47831, 43549, 40666, 38926, 29367, 24736, 205..."
WEEKDAY_APPR_PROCESS_START,object,0,7,NaN,NaN,NaN,NaN,"['TUESDAY', 'WEDNESDAY', 'MONDAY', 'FRIDAY', '...","[255118, 255010, 253557, 252048, 249099, 24063..."
HOUR_APPR_PROCESS_START,int64,0,24,0.000000e+00,1.248418e+01,23.000,3.334028,"[11, 12, 10, 13, 14, 15, 9, 16, 17, 8]","[192728, 185980, 181690, 172256, 157711, 14296..."
FLAG_LAST_APPL_PER_CONTRACT,int64,0,2,0.000000e+00,9.949258e-01,1.000,0.071052,"[1, 0]","[1661739, 8475]"
NFLAG_LAST_APPL_IN_DAY,int64,0,2,0.000000e+00,9.964675e-01,1.000,0.059330,"[1, 0]","[1664314, 5900]"
RATE_DOWN_PAYMENT,float64,895844,207033,-1.497876e-05,7.963682e-02,1.000,0.107823,"[0.0, 0.1089090909090909, 0.2178181818181818, ...","[369854, 36341, 6482, 1081, 746, 449, 304, 258..."
RATE_INTEREST_PRIMARY,float64,1664263,148,3.478125e-02,1.883569e-01,1.000,0.087671,"[0.1891363481808909, 0.14244021307945146, 0.16...","[1218, 951, 821, 681, 573, 241, 210, 204, 187,..."
RATE_INTEREST_PRIVILEGED,float64,1664263,25,3.731501e-01,7.735025e-01,1.000,0.100879,"[0.8350951374207188, 0.715644820295983, 0.6379...","[1717, 1046, 1039, 931, 876, 127, 66, 45, 40, 19]"
NAME_CASH_LOAN_PURPOSE,object,0,25,NaN,NaN,NaN,NaN,"['XAP', 'XNA', 'Repairs', 'Other', 'Urgent nee...","[922661, 677918, 23765, 15608, 8412, 2888, 269..."
NAME_CONTRACT_STATUS,object,0,4,NaN,NaN,NaN,NaN,"['Approved', 'Canceled', 'Refused', 'Unused of...","[1036781, 316319, 290678, 26436]"
DAYS_DECISION,int64,0,2922,-2.922000e+03,-8.806797e+02,-1.000,779.099667,"[-245, -238, -210, -273, -196, -224, -252, -18...","[2444, 2390, 2375, 2350, 2315, 2305, 2300, 228..."
NAME_PAYMENT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Cash through the bank', 'XNA', 'Non-cash fro...","[1033552, 627384, 8193, 1085]"
CODE_REJECT_REASON,object,0,9,NaN,NaN,NaN,NaN,"['XAP', 'HC', 'LIMIT', 'SCO', 'CLIENT', 'SCOFR...","[1353093, 175231, 55680, 37467, 26436, 12811, ..."
NAME_TYPE_SUITE,object,820405,7,NaN,NaN,NaN,NaN,"['Unaccompanied', 'Family', 'Spouse, partner',...","[508970, 213263, 67069, 31566, 17624, 9077, 2240]"
NAME_CLIENT_TYPE,object,0,4,NaN,NaN,NaN,NaN,"['Repeater', 'New', 'Refreshed', 'XNA']","[1231261, 301363, 135649, 1941]"
NAME_GOODS_CATEGORY,object,0,28,NaN,NaN,NaN,NaN,"['XNA', 'Mobile', 'Consumer Electronics', 'Com...","[950809, 224708, 121576, 105769, 99441, 53656,..."
NAME_PORTFOLIO,object,0,5,NaN,NaN,NaN,NaN,"['POS', 'Cash', 'XNA', 'Cards', 'Cars']","[691011, 461563, 372230, 144985, 425]"
NAME_PRODUCT_TYPE,object,0,3,NaN,NaN,NaN,NaN,"['XNA', 'x-sell', 'walk-in']","[1063666, 456287, 150261]"
CHANNEL_TYPE,object,0,8,NaN,NaN,NaN,NaN,"['Credit and cash offices', 'Country-wide', 'S...","[719968, 494690, 212083, 108528, 71297, 57046,..."
SELLERPLACE_AREA,int64,0,2097,-1.000000e+00,3.139511e+02,4000000.000,7127.443459,"[-1, 0, 50, 30, 20, 100, 40, 25, 15, 150]","[762675, 60523, 37401, 34423, 33840, 31409, 24..."
NAME_SELLER_INDUSTRY,object,0,11,NaN,NaN,NaN,NaN,"['XNA', 'Consumer electronics', 'Connectivity'...","[855720, 398265, 276029, 57849, 29781, 23949, ..."
CNT_PAYMENT,float64,372230,49,0.000000e+00,1.605408e+01,84.000,14.567288,"[12.0, 6.0, 0.0, 10.0, 24.0, 18.0, 36.0, 60.0,...","[323049, 190461, 144985, 141851, 137764, 77430..."
NAME_YIELD_GROUP,object,0,5,NaN,NaN,NaN,NaN,"['XNA', 'middle', 'high', 'low_normal', 'low_a...","[517215, 385532, 353331, 322095, 92041]"
PRODUCT_COMBINATION,object,346,17,NaN,NaN,NaN,NaN,"['Cash', 'POS household with interest', 'POS m...","[285990, 263622, 220670, 143883, 130248, 11258..."
DAYS_FIRST_DRAWING,float64,673065,2838,-2.922000e+03,3.422099e+05,365243.000,88916.115834,"[365243.0, -228.0, -224.0, -212.0, -223.0, -22...","[934444, 123, 121, 121, 119, 118, 117, 117, 11..."
DAYS_FIRST_DUE,float64,673065,2892,-2.892000e+03,1.382627e+04,365243.000,72444.869708,"[365243.0, -334.0, -509.0, -208.0, -330.0, -29...","[40645, 772, 760, 751, 750, 746, 745, 744, 744..."
DAYS_LAST_DUE_1ST_VERSION,float64,673065,4605,-2.801000e+03,3.376777e+04,365243.000,106857.034789,"[365243.0, 9.0, 8.0, 0.0, 5.0, 10.0, 2.0, 1.0,...","[93864, 720, 706, 705, 702, 698, 688, 685, 685..."
DAYS_LAST_DUE,float64,673065,2873,-2.889000e+03,7.658240e+04,365243.000,149647.415123,"[365243.0, -245.0, -188.0, -239.0, -167.0, -24...","[211221, 658, 650, 642, 638, 629, 627, 624, 62..."
DAYS_TERMINATION,float64,673065,2830,-2.874000e+03,8.199234e+04,365243.000,153303.516729,"[365243.0, -233.0, -170.0, -184.0, -163.0, -16...","[225913, 786, 770, 770, 769, 760, 754, 753, 74..."
NFLAG_INSURED_ON_APPROVAL,float64,673065,2,0.000000e+00,3.325702e-01,1.000,0.471134,"[0.0, 1.0]","[665527, 331622]"

In [4]:
ids = df.SK_ID_CURR.unique()

In [5]:
tmp = df[df.SK_ID_CURR==np.random.choice(ids)]
tmp

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1268243,1152292,247979,Consumer loans,12445.155,66645.0,66658.5,3330.0,66645.0,SATURDAY,8,1,1,0.051818,NaN,NaN,XAP,Approved,-922,Cash through the bank,XAP,Unaccompanied,New,Consumer Electronics,POS,XNA,Regional / Local,157,Consumer electronics,6.0,middle,POS household with interest,365243.0,-891.0,-741.0,-771.0,-767.0,0.0
890714,1845921,247979,Cash loans,17902.575,229500.0,248130.0,NaN,229500.0,SUNDAY,8,1,1,NaN,NaN,NaN,XNA,Approved,-263,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,18.0,middle,Cash X-Sell: middle,365243.0,-233.0,277.0,365243.0,365243.0,1.0
1142429,1927373,247979,Cash loans,NaN,0.0,0.0,NaN,NaN,SUNDAY,8,1,1,NaN,NaN,NaN,XNA,Canceled,-263,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
1370950,2529777,247979,Cash loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,8,1,1,NaN,NaN,NaN,XNA,Canceled,-195,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
tmp = df[df.SK_ID_CURR==100006]
tmp

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1131133,1020698,100006,Cash loans,39954.51,454500.00,481495.5,NaN,454500.00,SATURDAY,12,1,1,NaN,NaN,NaN,XNA,Approved,-438,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,18.0,high,Cash X-Sell: high,NaN,NaN,NaN,NaN,NaN,NaN
1232752,1243599,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,1,1,NaN,NaN,NaN,XNA,Canceled,-181,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
900957,1489396,100006,Revolving loans,13500.00,270000.00,270000.0,NaN,270000.00,THURSDAY,15,1,1,NaN,NaN,NaN,XAP,Approved,-181,XNA,XAP,Unaccompanied,Repeater,XNA,Cards,x-sell,Credit and cash offices,-1,XNA,0.0,XNA,Card X-Sell,365243.0,365243.0,365243.0,365243.0,365243.0,0.0
1607443,1697039,100006,Cash loans,32696.10,688500.00,906615.0,NaN,688500.00,THURSDAY,15,1,1,NaN,NaN,NaN,XNA,Refused,-181,Cash through the bank,LIMIT,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,48.0,low_normal,Cash X-Sell: low,NaN,NaN,NaN,NaN,NaN,NaN
98162,2078043,100006,Cash loans,24246.00,675000.00,675000.0,NaN,675000.00,THURSDAY,15,1,1,NaN,NaN,NaN,XNA,Approved,-181,Cash through the bank,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,48.0,low_normal,Cash X-Sell: low,365243.0,-151.0,1259.0,-151.0,-143.0,0.0
830967,2190416,100006,Consumer loans,29027.52,334917.00,267930.0,66987.00,334917.00,SUNDAY,15,1,1,0.217830,NaN,NaN,XAP,Approved,-311,Cash through the bank,XAP,Family,Repeater,Audio/Video,POS,XNA,Country-wide,8025,Consumer electronics,12.0,high,POS household with interest,365243.0,-281.0,49.0,365243.0,365243.0,0.0
1333657,2299329,100006,Consumer loans,2482.92,26912.34,24219.0,2693.34,26912.34,TUESDAY,15,1,1,0.108994,NaN,NaN,XAP,Approved,-617,XNA,XAP,NaN,New,Construction Materials,POS,XNA,Stone,30,Construction,12.0,middle,POS industry with interest,365243.0,-545.0,-215.0,-425.0,-416.0,0.0
1595430,2545789,100006,Cash loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,1,1,NaN,NaN,NaN,XNA,Canceled,-181,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
617859,2827850,100006,Revolving loans,NaN,0.00,0.0,NaN,NaN,THURSDAY,15,1,1,NaN,NaN,NaN,XAP,Canceled,-181,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN