In [1]:
import os
import numpy as np
import pandas as pd
import gc
from multiprocessing import Pool
from glob import glob
import utils
import EDA
sorted(glob('../data/*'))

['../data/101_test',
 '../data/101_train',
 '../data/102-1_test',
 '../data/102-1_train',
 '../data/102-2_test',
 '../data/102-2_train',
 '../data/102-3_CHANNEL_TYPE_test',
 '../data/102-3_CHANNEL_TYPE_train',
 '../data/102-3_CODE_REJECT_REASON_test',
 '../data/102-3_CODE_REJECT_REASON_train',
 '../data/102-3_NAME_CASH_LOAN_PURPOSE_test',
 '../data/102-3_NAME_CASH_LOAN_PURPOSE_train',
 '../data/102-3_NAME_CLIENT_TYPE_test',
 '../data/102-3_NAME_CLIENT_TYPE_train',
 '../data/102-3_NAME_CONTRACT_STATUS_test',
 '../data/102-3_NAME_CONTRACT_STATUS_train',
 '../data/102-3_NAME_CONTRACT_TYPE_test',
 '../data/102-3_NAME_CONTRACT_TYPE_train',
 '../data/102-3_NAME_GOODS_CATEGORY_test',
 '../data/102-3_NAME_GOODS_CATEGORY_train',
 '../data/102-3_NAME_PAYMENT_TYPE_test',
 '../data/102-3_NAME_PAYMENT_TYPE_train',
 '../data/102-3_NAME_PORTFOLIO_test',
 '../data/102-3_NAME_PORTFOLIO_train',
 '../data/102-3_NAME_PRODUCT_TYPE_test',
 '../data/102-3_NAME_PRODUCT_TYPE_train',
 '../data/102-3_NAME_SELLER_INDUSTRY_test',
 '../data/102-3_NAME_SELLER_INDUSTRY_train',
 '../data/102-3_NAME_TYPE_SUITE_test',
 '../data/102-3_NAME_TYPE_SUITE_train',
 '../data/102-3_NAME_YIELD_GROUP_test',
 '../data/102-3_NAME_YIELD_GROUP_train',
 '../data/102-3_PRODUCT_COMBINATION_test',
 '../data/102-3_PRODUCT_COMBINATION_train',
 '../data/102-3_SK_ID_PREV_test',
 '../data/102-3_SK_ID_PREV_train',
 '../data/102-3_WEEKDAY_APPR_PROCESS_START_test',
 '../data/102-3_WEEKDAY_APPR_PROCESS_START_train',
 '../data/103-1_test',
 '../data/103-1_train',
 '../data/103-2_test',
 '../data/103-2_train',
 '../data/103-3_test',
 '../data/103-3_train',
 '../data/104-1_test',
 '../data/104-1_train',
 '../data/104-2_test',
 '../data/104-2_train',
 '../data/104-3_test',
 '../data/104-3_train',
 '../data/105-1_train',
 '../data/105-2_test',
 '../data/105-2_train',
 '../data/106-1_test',
 '../data/106-1_train',
 '../data/106-2_test',
 '../data/106-2_train',
 '../data/106-3_test',
 '../data/106-3_train',
 '../data/107_test',
 '../data/107_train',
 '../data/108_CHANNEL_TYPE_test',
 '../data/108_CHANNEL_TYPE_train',
 '../data/108_CODE_REJECT_REASON_test',
 '../data/108_CODE_REJECT_REASON_train',
 '../data/108_NAME_CASH_LOAN_PURPOSE_test',
 '../data/108_NAME_CASH_LOAN_PURPOSE_train',
 '../data/108_NAME_CLIENT_TYPE_test',
 '../data/108_NAME_CLIENT_TYPE_train',
 '../data/108_NAME_CONTRACT_STATUS_test',
 '../data/108_NAME_CONTRACT_STATUS_train',
 '../data/108_NAME_CONTRACT_TYPE_test',
 '../data/108_NAME_CONTRACT_TYPE_train',
 '../data/108_NAME_GOODS_CATEGORY_test',
 '../data/108_NAME_GOODS_CATEGORY_train',
 '../data/108_NAME_PAYMENT_TYPE_test',
 '../data/108_NAME_PAYMENT_TYPE_train',
 '../data/108_NAME_PORTFOLIO_test',
 '../data/108_NAME_PORTFOLIO_train',
 '../data/108_NAME_PRODUCT_TYPE_test',
 '../data/108_NAME_PRODUCT_TYPE_train',
 '../data/108_NAME_SELLER_INDUSTRY_test',
 '../data/108_NAME_SELLER_INDUSTRY_train',
 '../data/108_NAME_TYPE_SUITE_test',
 '../data/108_NAME_TYPE_SUITE_train',
 '../data/108_NAME_YIELD_GROUP_test',
 '../data/108_NAME_YIELD_GROUP_train',
 '../data/108_PRODUCT_COMBINATION_test',
 '../data/108_PRODUCT_COMBINATION_train',
 '../data/108_WEEKDAY_APPR_PROCESS_START_test',
 '../data/108_WEEKDAY_APPR_PROCESS_START_train',
 '../data/109-1_test',
 '../data/109-1_train',
 '../data/109-2_test',
 '../data/109-2_train',
 '../data/110_test',
 '../data/110_train',
 '../data/POS_CASH_balance',
 '../data/bureau',
 '../data/bureau_balance',
 '../data/credit_card_balance',
 '../data/installments_payments',
 '../data/label',
 '../data/previous_application',
 '../data/sub.p',
 '../data/test',
 '../data/train']

In [2]:
keys = ['SK_ID_CURR', 'SK_ID_PREV' ]

In [12]:
pre = utils.read_pickles('../data/previous_application', keys+['NAME_CONTRACT_TYPE', 'NAME_CONTRACT_STATUS']).drop_duplicates()

100%|██████████| 20/20 [00:06<00:00,  2.93it/s]

In [3]:

pos = utils.read_pickles('../data/POS_CASH_balance', keys).drop_duplicates()
ins = utils.read_pickles('../data/installments_payments', keys).drop_duplicates()
cre = utils.read_pickles('../data/credit_card_balance', keys).drop_duplicates()

100%|██████████| 20/20 [00:07<00:00,  2.51it/s]
100%|██████████| 20/20 [00:08<00:00,  2.49it/s]
100%|██████████| 20/20 [00:11<00:00,  1.76it/s]
100%|██████████| 20/20 [00:08<00:00,  2.41it/s]

In [8]:
pos['from'] = 'pos'
ins['from'] = 'ins'
cre['from'] = 'cre'

In [13]:
pd.merge(pre, pos, on=keys, how='outer')

         SK_ID_CURR  SK_ID_PREV NAME_CONTRACT_TYPE NAME_CONTRACT_STATUS from
0            271877     2030495     Consumer loans             Approved  pos
1            108129     2802425         Cash loans             Approved  pos
2            122040     2523466         Cash loans             Approved  pos
3            176158     2819243         Cash loans             Approved  pos
4            202054     1784265         Cash loans              Refused  NaN
5            199383     1383531         Cash loans             Approved  pos
6            175704     2315218         Cash loans             Canceled  NaN
7            296299     1656711         Cash loans             Canceled  NaN
8            342292     2367563         Cash loans             Canceled  NaN
9            334349     2579447         Cash loans             Canceled  NaN
10           447712     1715995         Cash loans             Approved  pos
11           161140     2257824         Cash loans             Approved  pos
12           258628     2330894         Cash loans             Approved  pos
13           321676     1397919     Consumer loans             Approved  pos
14           270658     2273188     Consumer loans             Approved  pos
15           151612     1232483     Consumer loans             Approved  pos
16           154602     2163253     Consumer loans             Approved  pos
17           142748     1285768    Revolving loans             Approved  NaN
18           396305     2393109         Cash loans             Approved  NaN
19           199178     1173070         Cash loans              Refused  NaN
20           166490     1506815         Cash loans              Refused  NaN
21           267782     1182516         Cash loans             Approved  pos
22           302212     1172842         Cash loans              Refused  NaN
23           302212     1172937         Cash loans              Refused  NaN
24           199353     1555330         Cash loans             Canceled  NaN
25           275707     1543131         Cash loans             Approved  pos
26           338725     2536650         Cash loans             Approved  pos
27           433469     1676258         Cash loans             Approved  pos
28           418383     2075578     Consumer loans             Approved  pos
29           315664     1583704         Cash loans              Refused  NaN
...             ...         ...                ...                  ...  ...
1707606      417468     1212085                NaN                  NaN  pos
1707607      361017     1492989                NaN                  NaN  pos
1707608      108028     1333464                NaN                  NaN  pos
1707609      340014     1233575                NaN                  NaN  pos
1707610      268864     1896816                NaN                  NaN  pos
1707611      277245     1574474                NaN                  NaN  pos
1707612      127495     2619420                NaN                  NaN  pos
1707613      328218     1625221                NaN                  NaN  pos
1707614      380353     1165587                NaN                  NaN  pos
1707615      392486     2309667                NaN                  NaN  pos
1707616      179768     2552424                NaN                  NaN  pos
1707617      243281     2447703                NaN                  NaN  pos
1707618      373904     1523035                NaN                  NaN  pos
1707619      137246     1611054                NaN                  NaN  pos
1707620      441353     2399213                NaN                  NaN  pos
1707621      147941     1169157                NaN                  NaN  pos
1707622      243202     2439176                NaN                  NaN  pos
1707623      202049     2220759                NaN                  NaN  pos
1707624      253942     1739370                NaN                  NaN  pos
1707625      371169     1065058                NaN                  NaN  pos
1707626      371101     1339159                NaN                  NaN  pos
1707627      307985     2777392                NaN                  NaN  pos
1707628      307985     1271342                NaN                  NaN  pos
1707629      245695     1028428                NaN                  NaN  pos
1707630      238335     1031383                NaN                  NaN  pos
1707631      200989     2275502                NaN                  NaN  pos
1707632      199658     1434549                NaN                  NaN  pos
1707633      240630     2700857                NaN                  NaN  pos
1707634      338704     2318414                NaN                  NaN  pos
1707635      130741     1716103                NaN                  NaN  pos

[1707636 rows x 5 columns]

In [10]:
pre.shape

(1670214, 3)

In [14]:
train = utils.load_train()

100%|██████████| 20/20 [00:04<00:00,  4.86it/s]

In [15]:
train.sample(999).to_csv('train_sample.csv', index=False)

In [17]:
utils.read_pickles('../data/previous_application').sample(999).to_csv('pre_sample.csv', index=False)

100%|██████████| 20/20 [00:07<00:00,  2.76it/s]