In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from tqdm import tqdm
import lightgbm as lgb
import utils

In [2]:
train = utils.load_train()
test = utils.load_test()
prev = utils.read_pickles('../data/previous_application')

100%|██████████| 20/20 [00:05<00:00,  3.62it/s]
100%|██████████| 20/20 [00:01<00:00, 11.14it/s]
100%|██████████| 20/20 [00:38<00:00,  1.93s/it]

In [3]:
prev =prev[prev.NAME_CONTRACT_STATUS=='Approved'].drop('NAME_CONTRACT_STATUS', axis=1)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,past_payment_89m,past_payment_90m,past_payment_91m,past_payment_92m,past_payment_93m,past_payment_94m,past_payment_95m,past_payment_96m,past_payment_97m,APP_CREDIT_PERC
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,0.0,607500.0,THURSDAY,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.893815
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,0.0,112500.0,TUESDAY,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.824511
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,0.0,450000.0,MONDAY,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.955840
5,1383531,199383,Cash loans,23703.930,315000.0,340573.5,0.0,315000.0,SATURDAY,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.924910
10,1715995,447712,Cash loans,11368.620,270000.0,335754.0,0.0,270000.0,FRIDAY,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.804160
11,2257824,161140,Cash loans,13832.775,211500.0,246397.5,0.0,211500.0,FRIDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.858369
12,2330894,258628,Cash loans,12165.210,148500.0,174361.5,0.0,148500.0,TUESDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.851679
13,1397919,321676,Consumer loans,7654.860,53779.5,57564.0,0.0,53779.5,SUNDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.934256
14,2273188,270658,Consumer loans,9644.220,26550.0,27252.0,0.0,26550.0,SATURDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.974240
15,1232483,151612,Consumer loans,21307.455,126490.5,119853.0,12649.5,126490.5,TUESDAY,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.055380
16,2163253,154602,Consumer loans,4187.340,26955.0,27297.0,1350.0,26955.0,SATURDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.987471
17,1285768,142748,Revolving loans,9000.000,180000.0,180000.0,0.0,180000.0,FRIDAY,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
18,2393109,396305,Cash loans,10181.700,180000.0,180000.0,0.0,180000.0,THURSDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
21,1182516,267782,Cash loans,20361.600,405000.0,451777.5,0.0,405000.0,SATURDAY,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.896459
25,1543131,275707,Cash loans,22619.520,229500.0,241920.0,0.0,229500.0,THURSDAY,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.948661
26,2536650,338725,Cash loans,16708.320,369000.0,369000.0,0.0,369000.0,WEDNESDAY,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
27,1676258,433469,Cash loans,22242.825,247500.0,268083.0,0.0,247500.0,THURSDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.923222
28,2075578,418383,Consumer loans,7656.705,74610.0,65610.0,9000.0,74610.0,MONDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.137174
30,2138466,170289,Consumer loans,3286.485,32562.0,32562.0,0.0,32562.0,FRIDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
31,2191093,182450,Consumer loans,9789.255,100485.0,100485.0,0.0,100485.0,WEDNESDAY,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
34,1629736,255331,Revolving loans,10125.000,202500.0,202500.0,0.0,202500.0,SATURDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
35,2027074,208000,Consumer loans,12065.535,56655.0,66411.0,0.0,56655.0,SATURDAY,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.853097
37,1151694,161591,Consumer loans,39111.075,214380.0,209497.5,13500.0,214380.0,FRIDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.023306
38,1692577,125157,Consumer loans,9946.485,99319.5,109809.0,0.0,99319.5,SATURDAY,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.904475
39,2740958,281589,Consumer loans,6752.250,35955.0,33115.5,4500.0,35955.0,THURSDAY,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.085745
40,2317570,258076,Consumer loans,4539.285,18360.0,21834.0,0.0,18360.0,WEDNESDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.840890
42,2319873,188414,Consumer loans,3560.715,71356.5,76410.0,7573.5,71356.5,FRIDAY,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.933863
43,2057616,304455,Consumer loans,15542.730,129505.5,131112.0,9000.0,129505.5,WEDNESDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.987747
44,2675386,118974,Consumer loans,6899.490,55831.5,60745.5,0.0,55831.5,SUNDAY,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.919105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670041,2174267,107157,Cash loans,45495.810,900000.0,1004544.0,0.0,900000.0,WEDNESDAY,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.895929
1670056,2737753,295861,Cash loans,25996.365,337500.0,384277.5,0.0,337500.0,TUESDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.878272
1670070,1532278,205251,Cash loans,27996.390,540000.0,604152.0,0.0,540000.0,SATURDAY,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.893815
1670076,1302084,134595,Cash loans,7395.480,90000.0,98910.0,0.0,90000.0,TUESDAY,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.909918
1670084,1761896,178942,Cash loans,81323.685,454500.0,454500.0,0.0,454500.0,FRIDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1670086,2328654,262361,Cash loans,47258.820,1026000.0,1115383.5,0.0,1026000.0,THURSDAY,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.919863
1670098,2357182,320283,Cash loans,14182.380,270000.0,313839.0,0.0,270000.0,SUNDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.860314
1670132,1226722,306973,Cash loans,6087.015,90000.0,109008.0,0.0,90000.0,WEDNESDAY,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.825627
1670135,1793983,406318,Cash loans,41562.180,1125000.0,1288350.0,0.0,1125000.0,TUESDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.873210
1670146,1614343,315728,Cash loans,83758.275,2025000.0,2169342.0,0.0,2025000.0,SUNDAY,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.933463
1670150,1556936,169693,Cash loans,18852.435,90000.0,92970.0,0.0,90000.0,THURSDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.968054
1670159,2354512,393355,Cash loans,20380.500,450000.0,450000.0,0.0,450000.0,WEDNESDAY,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1670175,1176409,247954,Cash loans,9740.250,135000.0,135000.0,0.0,135000.0,THURSDAY,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1670177,2486989,391517,Cash loans,20876.805,270000.0,299223.0,0.0,270000.0,SUNDAY,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.902337
1670178,1406116,239526,Cash loans,24764.400,270000.0,270000.0,0.0,270000.0,THURSDAY,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1670192,2101747,339383,Revolving loans,3375.000,NaN,67500.0,0.0,NaN,FRIDAY,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1670194,2101748,280792,Cash loans,10482.795,90000.0,107604.0,0.0,90000.0,MONDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.836400
1670195,2561520,334654,Consumer loans,24851.025,248535.0,223681.5,24853.5,248535.0,FRIDAY,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111111
1670198,1540903,212968,Consumer loans,2088.495,22869.0,20578.5,2290.5,22869.0,SUNDAY,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.111305
1670199,1077969,242303,Consumer loans,8546.940,37926.0,40932.0,0.0,37926.0,THURSDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.926561
1670200,1024416,331038,Cash loans,7576.920,99000.0,112068.0,0.0,99000.0,FRIDAY,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.883392
1670201,1028905,442706,Consumer loans,6127.065,45450.0,54126.0,2295.0,45450.0,MONDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.839707
1670202,2205099,157707,Consumer loans,4334.355,22207.5,23854.5,0.0,22207.5,THURSDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.930956
1670206,2459206,238591,Cash loans,19401.435,180000.0,243936.0,0.0,180000.0,TUESDAY,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.737898
1670208,1556789,209732,Cash loans,22299.390,315000.0,436216.5,0.0,315000.0,THURSDAY,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.722118
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.858367
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.364877
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.026467
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,0.0,180000.0,WEDNESDAY,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.938086
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,0.0,360000.0,SUNDAY,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [3]:
col_cat = [c for c in prev.columns if prev[c].dtype=='O']

In [4]:
prev = pd.get_dummies(prev, columns=col_cat, drop_first=True)

In [5]:
tmp = pd.merge(prev, train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [6]:
prev_tr = tmp[~tmp.TARGET.isnull()]
prev_te = tmp[tmp.TARGET.isnull()]

In [7]:
tmp  = prev_tr[['SK_ID_CURR']].set_index('SK_ID_CURR')
tmp['y'] = prev_tr.TARGET
tmp['cnt'] = prev_tr['SK_ID_CURR'].value_counts()
tmp['w'] = tmp['y'].values / tmp.cnt.values

In [9]:
tmp['g'] = tmp.index % 5

In [11]:
tmp.g.value_counts()

1    283869
2    283237
0    283186
4    282292
3    281117
Name: g, dtype: int64

In [12]:
X_tr = prev_tr.drop(['SK_ID_PREV', 'SK_ID_CURR', 'TARGET'], axis=1).reset_index(drop=True)
tmp.reset_index(inplace=True)

In [13]:
X_tr.shape

(1413701, 448)

In [14]:
tmp.shape

(1413701, 5)

In [18]:
from sklearn.model_selection import GroupKFold

In [19]:
group_kfold = GroupKFold(n_splits=5)

In [24]:
index = []
for train_index, test_index in group_kfold.split(X_tr, tmp.y, tmp.g):
    index.append([train_index.shape, test_index.shape])

# CV

In [15]:
SEED = 71

param = {
         'objective': 'binary',
         'metric': 'auc',
         'learning_rate': 0.2,
         'max_depth': 6,
         'num_leaves': 63,
         'max_bin': 255,
         
         'min_child_weight': 10,
         'min_data_in_leaf': 150,
         'reg_lambda': 0.5,  # L2 regularization term on weights.
         'reg_alpha': 0.5,  # L1 regularization term on weights.
         
         'colsample_bytree': 0.9,
         'subsample': 0.9,
#         'nthread': 32,
         'nthread': 64,
         'bagging_freq': 1,
         'verbose':-1,
         'seed': SEED
         }

In [25]:
dtrain = lgb.Dataset(X_tr, tmp.y)

In [28]:
ret = lgb.cv(param, dtrain, 9999, folds=group_kfold.split(X_tr, tmp.y, tmp.g), 
             stratified=False,
             early_stopping_rounds=100, verbose_eval=50,
             seed=SEED)

ValueError: too many values to unpack (expected 2)

In [30]:
for train_index, test_index in group_kfold.split(X_tr, tmp.y, tmp.g):
    dtrain = lgb.Dataset(X_tr.iloc[train_index], tmp.iloc[train_index].y)
    dvalid = lgb.Dataset(X_tr.iloc[test_index], tmp.iloc[test_index].y)
    
    model = lgb.train(params=param, train_set=dtrain, num_boost_round=9999, 
                  valid_sets=[dtrain, dvalid], 
                  valid_names=['train','valid'], 
                  early_stopping_rounds=100, 
                  #evals_result=evals_result, 
                  verbose_eval=50
                  )

Training until validation scores don't improve for 100 rounds.
[50]	train's auc: 0.576242	valid's auc: 0.413648
[100]	train's auc: 0.616871	valid's auc: 0.417794
Early stopping, best iteration is:
[2]	train's auc: 0.447365	valid's auc: 0.424563
Training until validation scores don't improve for 100 rounds.
[50]	train's auc: 0.56949	valid's auc: 0.403495
[100]	train's auc: 0.616352	valid's auc: 0.401283
Early stopping, best iteration is:
[3]	train's auc: 0.465433	valid's auc: 0.416624
Training until validation scores don't improve for 100 rounds.
[50]	train's auc: 0.572386	valid's auc: 0.417389
[100]	train's auc: 0.617512	valid's auc: 0.418305
Early stopping, best iteration is:
[9]	train's auc: 0.483983	valid's auc: 0.420909
Training until validation scores don't improve for 100 rounds.
[50]	train's auc: 0.57654	valid's auc: 0.426724
[100]	train's auc: 0.619956	valid's auc: 0.423378
Early stopping, best iteration is:
[47]	train's auc: 0.571848	valid's auc: 0.426947
Training until validation scores don't improve for 100 rounds.
[50]	train's auc: 0.562204	valid's auc: 0.416815
[100]	train's auc: 0.603921	valid's auc: 0.421043
Early stopping, best iteration is:
[4]	train's auc: 0.455895	valid's auc: 0.4228